### ISSUE TITLE
Add ability to disable saving changes to disk

### ISSUE THREAD

**Issue by Aaronm14** [opticdev/optic#1]
Goal would be to create a flag that allows extensions to explicitly disable saving to disk when you register the connection. Should be a query parameter like /editors/atom?autorefresh=true

**Comment by acunniffe** [comment]
Hey Aaron, 

This makes good sense to me. I can see how always saving changes to disk might confuse some editors. It could possibly cause race conditions if Optic sends a files updated before/after the editor is notified of the disk changes. 

There's a new feature branch for this that passes all tests, I'll incorporate it in the release coming out this week. [feature/autorefreshededitorflag](https://github.com/opticdev/optic/commit/4c9eea1c420b2124404a1a9ae1cc08a2f6f402f4)

I've also pushed a new version of the [editor sdk](https://github.com/opticdev/optic-editor-javascript-sdk). You can get it on the node registry as version 0.1.8. 

To use it just pass an option called autorefreshes (it's a boolean, optional and defaults to false)
```javascript
EditorConnection({name: 'vscode', autorefreshes: true})
```

Here's a link to a [snapshot build of the Optic App with the changes implemented](https://drive.google.com/file/d/14qS62xB9Cif0WvwinKmD2r3Dop4AInRd/view?usp=sharing). Can you test your plugin against this build before the release Wednesday and let me know if it works as expected?

**Comment by acunniffe** [comment]
Great. Thanks for the help debugging! 🥇
