### ISSUE TITLE
Command api generate:oas not working

### ISSUE THREAD

**Issue by sivantha96** [opticdev/optic#1074]
I am trying to export as OpenAPI

```
Error: Cannot use GraphQLSchema "[object GraphQLSchema]" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
    at instanceOf (/usr/local/lib/node_modules/@useoptic/cli/node_modules/@useoptic/spectacle/node_modules/graphql/jsutils/instanceOf.js:28:13)
    at isSchema (/usr/local/lib/node_modules/@useoptic/cli/node_modules/@useoptic/spectacle/node_modules/graphql/type/schema.js:36:34)
    at assertSchema (/usr/local/lib/node_modules/@useoptic/cli/node_modules/@useoptic/spectacle/node_modules/graphql/type/schema.js:40:8)
    at validateSchema (/usr/local/lib/node_modules/@useoptic/cli/node_modules/@useoptic/spectacle/node_modules/graphql/type/validate.js:44:28)
    at graphqlImpl (/usr/local/lib/node_modules/@useoptic/cli/node_modules/@useoptic/spectacle/node_modules/graphql/graphql.js:79:62)
    at /usr/local/lib/node_modules/@useoptic/cli/node_modules/@useoptic/spectacle/node_modules/graphql/graphql.js:28:31
    at new Promise (<anonymous>)
    at Object.graphql (/usr/local/lib/node_modules/@useoptic/cli/node_modules/@useoptic/spectacle/node_modules/graphql/graphql.js:26:10)
    at Object.queryWrapper (/usr/local/lib/node_modules/@useoptic/cli/node_modules/@useoptic/spectacle/build/spectacle.js:488:26)
    at Object.generateOpenApi (/usr/local/lib/node_modules/@useoptic/cli/node_modules/@useoptic/spectacle/build/openapi/index.js:7:38)
```

**Comment by LouManglass** [comment]
Hi @sivantha96 ,

I'm sorry to see that issue. Would you mind letting me know:

- How did you install Optic? We recommend a [global installation](https://www.useoptic.com/document) so you can monitor any project. This will give us information on the scope of the dependencies.
- What version of Optic did you install? `api --version` may work if you don't recall.
- Is your project open-source? If so, please let me know against which project you were trying to run Optic and that will also help me investigate the dependencies at play.

We can definitely help you get your OAS export, and make this more robust for other users as well.

**Comment by LouManglass** [comment]
Hi @sivantha96 ,

I have some working theories I'm going to be investigating. Do you have more information on your installation for us so we can assure our fix will work for you?

**Comment by sivantha96** [comment]
Hi @LouManglass,

I installed it globally. I am afraid the project is not open-source. 

here's the output of `api --version`

```
@useoptic/cli/10.2.2 darwin-x64 node-v14.17.4
```

Thanks in advance.

**Comment by LouManglass** [comment]
@sivantha96 ,

We've identified the issue in our peer dependencies, as NPM has changed behavior with major version 7. We're currently working on cleaning up our dependencies so that it will install properly on both NPM 6 and 7. I'm sorry for the inconvenience.

In the mean time, you can force the NPM 6 peer dependency resolution process when installing Optic via an additional flag. The following should get you running while we finish the full fix:

`npm uninstall --global @useoptic/cli`
`npm install --global --legacy-peer-deps @useoptic/cli`

**Comment by LouManglass** [comment]
Tested a fix in #1099 which is now merged and should release Thursday. Going forward, there should be no need to specify `--legacy-peer-deps` on any version on NPM.

**Comment by LouManglass** [comment]
PR #1099 , after testing, worked great on all versions of NPM but broke Yarn installations and local development. We had to back it out and delayed release to re-evaluate.

For now,  npm install --global --legacy-peer-deps @useoptic/cli is the recommended way of installing successfully on NPM 7. We will revisit this with a more appropriate fix.

**Comment by rowantower** [comment]
Hi @LouManglass, thanks for your hint! I've bumped into the same issue with brew distributive. I was able to solve it with your work around but just a heads-up that the issue still exists.

**Comment by LouManglass** [comment]
@rowantower Thanks again for the heads-up: I updated the Brew formula to use the legacy peer dependencies flag. You can safely stay the course with the npm workaround here, I just wanted to say thanks and let you know your report helped improve the Brew installer.
