### ISSUE TITLE
Document optic.yaml command env vars on windows.

### ISSUE THREAD

**Issue by laundmo** [opticdev/optic#1106]
As per the documentation, you should start an API with the `$PORT` env var as part of the command. There is no mention in the documentation anywhere which would tell me that optic itself does not insert this env var, but relies on the operating system command line. This leads to, on Windows, errors like 
```
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: Invalid value for '--port' / '-p': '$PORT' is not a valid integer.
```

Please document that on windows `%PORT%`  has to be used, or alternatively, have optic insert the environment variable instead of relying on the OS commandline.

**Comment by LouManglass** [comment]
Howdy @laundmo ,

The environment variable is named `PORT`, and expansion depends on the platform. I can see why that's confusing, as the documentation assumes a POSIX style `$` instead of Windows' `%var%`. Sorry for the confusion, I'll make that clearer.

**Comment by LouManglass** [comment]
We're going to be revisiting the documentation in the coming weeks, incorporating feedback from the Discord community and users. In the mean time, I've added a port expansion hint to troubleshooting:

<img width="929" alt="image" src="https://user-images.githubusercontent.com/241059/129381972-9333d548-f476-4346-8bee-873a8821c0fb.png">

More changes will come to make this clearer in the next few weeks, and this will bridge a gap until then.

**Comment by laundmo** [comment]
î really dont think this belongs in troubleshooting. why not just add a small mention that on windows you need to do `%PORT%`?

**Comment by LouManglass** [comment]
@laundmo We will make a more holistic approach as we revisit documents in the coming weeks to make this clearer. We're going to simplify documentation with this and other feedback provided. The intent is to provide some help in the mean time, but not heavily invest in the current state - we agree, from our conversation in Discord, this could be simpler, and we want to look at the flow as a whole.
