### ISSUE TITLE
Content type is case sensitive when sending ecs object through api exec

### ISSUE THREAD

**Issue by silentninja** [opticdev/optic#1114]
When sending ecs object through api exec, the content type is recorded as null when sent in uppercase while getting recorded correctly when sent in lower case. As per [RFC 2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2l) headers are case insensitive.

**Comment by LouManglass** [comment]
Yes, I see, thanks for spotting that. We'll dig into it.
