### ISSUE TITLE
Changes are not getting recorded when sent through ecs ingestion mode

### ISSUE THREAD

**Issue by silentninja** [opticdev/optic#1115]
When sending ECS object to the optic server `ecs endpoint`, the changes are not getting recorded by optic, though the response is 201

Steps to reproduce:
1. Run command using api exec "<command>"
2. Send ecs json object to the URL from `OPTIC_LOGGING_URL` env 
3. Request is sent successfully and 201 is received 
4. API status returns ` No diffs observed for existing endpoints `

**Comment by LouManglass** [comment]
Good point. Thanks for the check, we'll look into it.

**Comment by acunniffe** [comment]
@silentninja I can reproduce this now. Looking at it today.
