### ISSUE TITLE
OpenAPI export is not populating the `summary` field

### ISSUE THREAD

**Issue by andrewsnowden** [opticdev/optic#1136]
When exporting my APIs using `api generate:oas`, Optic is not including the name of the API that I have set into the OpenAPI spec. I downgraded to version `9.0.8` and the export works as expected, setting the `summary` to be the name I set in the UI. If I upgrade to 10.0.1 (or later) then it breaks: the name I am setting in the UI doesn't appear anywhere in the generated OpenAPI specification.

Looking at past issues around this issue, my understanding is that this should be coming from the `purpose` key of the API, and looking at the `specification.json` in my project, this `purpose` is definitely set - and I did find some code that was attempting to set the `summary` to be equal to the `purpose`, so I've somewhat reached the end of what I can debug without having much of an understanding of the code base.

Thanks for the great project!

**Comment by LouManglass** [comment]
Hi @andrewsnowden 

Thanks for the nice words, and the detailed dive! We made some changes in how OpenAPI exports works by the time Optic 10 rolled around, and it looks like we may have missed something. I'll dig into this and tie in the folks who have the most experience in this part of the project to get more information. Expect a follow up this week with some next steps, or requesting some more information, so we can get this resolved.

**Comment by ViRb3** [comment]
Hello, just hit the same issue today when I was updating an old spec generated with Optic. My project depends on either the `OperationID` or `Summary` being populated with the endpoint name I have chosen in Optic. Is there any update on the situation? Thanks!

**Comment by LouManglass** [comment]
Hi @ViRb3,

Optic 10 is no longer under active development, as the latest Optic tools work directly with OpenAPI and can read existing files, edit them, and write the changes back out while preserving existing fields. If you haven't signed up to see the beta yet, [that would be my first suggestion](https://www.useoptic.com/). We can help you get migrated and show you all the new features and workflow improvements.
