### ISSUE TITLE
Ability to rename/remove endpoints from specification

### ISSUE THREAD

**Issue by dyc3** [opticdev/optic#1144]
# Problem

I recently renamed an endpoint's path on one of my projects. I re-documented the new endpoints, but I don't see an option in the web UI to remove the old endpoints.

# Desired solution

Ideally, I'd be able to tell optic that I renamed the endpoint. However, at minimum I would like to be able to remove the old endpoints.

**Comment by LouManglass** [comment]
@dyc3 I'm sorry this sat around, I missed the initial notification.

Please click **Edit** at the upper-right hand corner of the Docs screen, which should give you the option to delete any endpoint with a trash can icon after the endpoint name. You can also edit the detailed description of any endpoint, which should show a delete button at the top.

Currently you can't give Optic the context that an endpoint is being renamed. That's something we're looking into.

**Comment by Nagarjun30** [comment]
Hi @LouManglass ,

**Version**
 api --version 
@useoptic/cli/10.3.0 darwin-x64 node-v14.18.2

**Command Tried**
api generate:oas
 
The above command generate document details for the deleted endpoints in Optic specification. I can see the entries for **RequestRemoved** in specification.json file with the specific path  and method. 

**Specification.json**

> ,{"PathComponentAdded":{"pathId":"path_UX3ejWLvM","parentPathId":"path_svQH921jIy","name":"5","eventContext":{"clientId":"proud-treefrog-90","clientSessionId":"f624e858-d88b-41ef-aa68-93f348c2cea9","clientCommandBatchId":"72dd00fb-8391-4bd0-b0a5-a6115138b716","createdAt":"2022-01-02T21:50:22.378764+05:30"}}},
{"PathComponentAdded":{"pathId":"path_9djxwS_g2H","parentPathId":"path_UX3ejWLvM","name":"items","eventContext":{"clientId":"proud-treefrog-90","clientSessionId":"f624e858-d88b-41ef-aa68-93f348c2cea9","clientCommandBatchId":"72dd00fb-8391-4bd0-b0a5-a6115138b716","createdAt":"2022-01-02T21:50:22.378764+05:30"}}},
{"RequestAdded":{"requestId":"**request_tQG2hMg2cq**","pathId":"path_9djxwS_g2H","httpMethod":"GET","eventContext":{"clientId":"proud-treefrog-90","clientSessionId":"f624e858-d88b-41ef-aa68-93f348c2cea9","clientCommandBatchId":"72dd00fb-8391-4bd0-b0a5-a6115138b716","createdAt":"2022-01-02T21:50:22.378764+05:30"}}},
.
.
.
{"RequestRemoved":{"requestId":"**request_tQG2hMg2cq**","eventContext":{"clientId":"proud-treefrog-90","clientSessionId":"044c6e31-a55a-4bd8-af8f-c4c12022f08a","clientCommandBatchId":"9fe20cf3-3f99-4866-9e7d-fc546d985f88","createdAt":"2022-01-02T21:57:18.761302+05:30"}}}

**Generated YAML**

>  /todos/5/items:
  get:
   responses:
    '200':
     description: ''
     content:
      application/json:
       schema:
        type: array
        items: {}

**Comment by LouManglass** [comment]
Hi @Nagarjun30 ,

From what I can see, the OpenAPI exporter doesn't currently filter out endpoints deleted in the UI. I'm sorry about that! If you're primarily concerned with OpenAPI output, I'd encourage you to checkout our [beta program](https://www.useoptic.com/). In our latest version, you can work directly with OpenAPI which should make interoperability easier. If  you have any other questions, let me know.

**Comment by dyc3** [comment]
I'm confused, is this implemented?
