### ISSUE TITLE
[Security] Workflow build-ui-v2.yml is using vulnerable action aws-actions/amazon-ecr-login

### ISSUE THREAD

**Issue by qazaqstan2025** [opticdev/optic#1150]
The workflow build-ui-v2.yml is referencing action aws-actions/amazon-ecr-login using references 060516122e7b4cc1cc3d4614a998adbb93d3fbf2. However this reference is missing the commit [57206dc28c379a6eebdce44c592109d2e97e031d](https://github.com/aws-actions/amazon-ecr-login/commits/57206dc28c379a6eebdce44c592109d2e97e031d) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by LouManglass** [comment]
Thanks,

We're currently re-evaluating our actions and how we deliver our software to our users. We'll take this into account with the rest of our work.
