### ISSUE TITLE
Run optic as proxy or integrate with NGINX?

### ISSUE THREAD

**Issue by ross-nordstrom** [opticdev/optic#130]
It looks like older versions (v6 for example) had a command `api intercept`.  Is something like this still around?  My API has a mix of languages and not all of them use a framework you support, so operating at a proxy or nginx level would be fantastic for my team.

PS - I opened an [issue in the docs repo](https://github.com/opticdev/docs/issues/2), but that's probably the wrong place for this question.

**Comment by acunniffe** [comment]
Hey @ross-nordstrom the functionality is still there, but it isn’t documented. It looks like you scheduled a call with us Wednesday. Let’s figure out how to get you wired up and PR whatever we come back with back into the docs! 

Thanks for trying out the tool!

**Comment by ross-nordstrom** [comment]
Sounds good!
