### ISSUE TITLE
optic diff --web does not open browser when run in WSL - does not display URL to manually open.

### ISSUE THREAD

**Issue by laundmo** [opticdev/optic#1314]
I'm using Optic inside WSL, and when using the `optic diff --web` command it (expectedly) fails to open anything as WSL is a headless environment.

As a fix/workaround, please display the URL to open directly.

**Comment by acunniffe** [comment]
We'll look into using a better cross platform URL opener. I think I've seen one in the past that works with whatever browser is in the registry. 

Showing the URL is less useful than it may seem -- most of the browsers have a limit of the length of a URL, and even a modestly OpenAPI file (hundreds lines) surpasses it. For whatever reason those limits are not applied if you don't manually paste the URL into the address bar. However -- if it won't do either -- not useful. We'll look into this as a bug

**Comment by alexandre-orca** [comment]
Faced with the same issue. Any updates or ETA? IMO, showing URL would be useful for debug purpose.

**Comment by acunniffe** [comment]
Hey @alexandre-orca -- we are still trying to figure out a good approach here. Unfortunately when we print the URL it's often too long for browsers to accept. 

What version of WSL are you using? The library we use says it supports most WSL  opens https://www.npmjs.com/package/open?activeTab=readme

**Comment by alexandre-orca** [comment]
@acunniffe We are using Linux build machines so there no browser at all. Maybe you somehow can add saving request in some format (like cURL, [maybe using this](https://pkg.go.dev/moul.io/http2curl)).

**Comment by acunniffe** [comment]
Hey @alexandre-orca -- we recently added `optic diff ... --web --upload` which supports saving changelogs to your Optic Cloud account. This makes them easier to share / persist. We've still yet to find a good way to get this to open in every browser. 

We may one day support a local server that renders the diff, but it hasn't been a priority right now and we're a small team. Will that option work for you?
