### ISSUE TITLE
Property rules are not dry

### ISSUE THREAD

**Issue by acunniffe** [opticdev/optic#1321]
API Enablement teams I've been working with to define their own custom Optic rules have been duplicating a lot of code when writing rules about properties. 

The current rule engine treats Request and Response properties as separate, and they are for breaking changes, but for nearly every other kind of rule you want them to apply to both places. Having to write the rule twice is slowing folks down. 

Can we build a `PropertyRule` rule type to make this easier?

**Comment by niclim** [comment]
this has been added in `0.29.0`
