### ISSUE TITLE
Git must be available in PATH for "init" to work.

### ISSUE THREAD

**Issue by circleupx** [opticdev/optic#1391]
Hello, 

I'm testing our optic to see how it can be integrated into my workflow. I'm following the instructions outlined in [Optic CLI](https://www.useoptic.com/docs) but I am running into the following error when I initiate optic. 

> Error: git must be available in PATH for "init" to work.

I looked and Git is in my path and I can resolve it from the terminal.

![image](https://user-images.githubusercontent.com/8635797/198422288-c2e11587-e8fd-4479-8b83-005aaa647eff.png)

Any ideas on what might be the problem?

**Comment by circleupx** [comment]
Understood, thank you very much.

**Comment by acunniffe** [comment]
No problem. Closing this now #1392 fixes powershell as well.
