### ISSUE TITLE
Overly strict OpenAPI Spec 3.1 JsonSchema enforcement

### ISSUE THREAD

**Issue by SeanKeenan-at** [opticdev/optic#1600]
There are three properties I'm seeing fail: 
 - `const` (similar to `enum`)
 - `propertyNames` on objects
 - [unevaluatedProperties](https://json-schema.org/understanding-json-schema/reference/object.html#unevaluated-properties) on objects (Available in `2019-09`)

I believe while these were invalid in OpenAPI 3.0, 3.1 has brought closer alignment to the JSONSchema spec (and up to metaschema 2020-12) and I think the above should be valid. All of these also pass spectral lint.

I believe the changes need to be made to this file: `projects/openapi-io/src/validation/validation-schemas.ts`

**Comment by acunniffe** [comment]
Thanks @SeanKeenan-at -- we'll loosen up the validation around 3.1 keywords. 

It may be a while before anyone has time to write breaking change rules that take some of these keywords into account. They're probably easy to write code for, but difficult to think through the requirements for. If you have any interest in helping to think through that let us know. 

I'll update this issue later in the week once we have a release out

**Comment by SeanKeenan-at** [comment]
Wow, that was a fast response - thank you! And totally understand.

I think in-so-far as breaking changes:
 - I believe `const` can be treated _exactly_ as an `enum`, as long as you first convert the single element to an array. (As in, converting between `const: 'example'` and an `enum: ['example']` doesn't even need to be picked up as a change IMO).
 - `propertyNames` + `unevaluatedProperties` are a bit trickier to think through.

I threw up a PR for the `const` treatment if that's helpful! #1601
