### ISSUE TITLE
New endpoints are not detected if only the HTTP method is different.

### ISSUE THREAD

**Issue by dyc3** [opticdev/optic#1630]
**Describe the bug**
Sometimes, new endpoints don't get marked as undocumented if they only differ by the HTTP method

**To Reproduce**
1. Run optic to capture requests
2. Make request for `GET /foo`, `POST /foo`, `PATCH /foo`
3. Document `PATCH /foo`
4. Run optic verify
5. See that it thinks there are no undocumented requests.

**Expected behavior**

Expected to see `GET /foo`, and `POST /foo` marked as undocumented

**Screenshots**

**Details (please complete the following information):**
 - OS and version: debian bullseye devcontainer (docker image `mcr.microsoft.com/devcontainers/base:bullseye`)
 - Optic version: 0.38.0
 - NodeJS version: v18.14.0

**Additional context**
The repo I'm working with is here: https://github.com/dyc3/d6-survey-service/

**Comment by acunniffe** [comment]
Hey @dyc3 -- I was able to reproduce this and am working on a fix now. Will have it up tomorrow.

**Comment by acunniffe** [comment]
Can you try on https://github.com/opticdev/optic/releases/tag/v0.38.2-1?

**Comment by dyc3** [comment]
That release doesn't appear to fix the issue. I have a slightly different series of steps that produces the same result

1. Document `POST /foo`
2. Run optic to capture request for `GET /foo`
3. Run optic verify
4. See that it thinks there are no undocumented requests.

**Comment by acunniffe** [comment]
Interesting. I'll dive back in.

**Comment by acunniffe** [comment]
@dyc3 -- woah that was 100% a bug. we weren't passing in the current operations to the path inference so it would miss these https://github.com/opticdev/optic/pull/1631/files#diff-e90feac87ce67c4568c20d4463cdff6e6c8b2f17e6189f3dd05cb281bc0f445eL182-L183

Cutting a release now. Thanks for opening this issue. We have tests covering this functionality, but we weren't testing it end-end and obviously it won't work if it's not getting the correct inputs at runtime.

**Comment by acunniffe** [comment]
@dyc3  try 0.39.0 -- I made own GET/POST foo server is Rust and got a full repo / validated the fix

**Comment by dyc3** [comment]
Yup that fixes it. Thanks!
