### ISSUE TITLE
Broken GitHub link from useoptic.com

### ISSUE THREAD

**Issue by tobymurray** [opticdev/optic#1681]
**Describe the bug**
Just a heads up, the GitHub link in the top right on https://www.useoptic.com/ leads to https://github.com/opticdev/useoptic.com which 404's

**Comment by acunniffe** [comment]
Great catch. A fix is deploying now. Anything else I can help with?

**Comment by tobymurray** [comment]
Nope, just noticed the dead link - thanks.
