### ISSUE TITLE
JSON Schema closeness to ignore annotations?

### ISSUE THREAD

**Issue by MikeRalphson** [opticdev/optic#1777]
**Describe the enhancement**
In the [closeness](https://github.com/opticdev/optic/blob/main/projects/openapi-cli/src/shapes/closeness/closeness.ts) module, the intersection of common properties is computed, but no differentiation is made between applicators, assertions and annotations as far as I can see.

**Comment by MikeRalphson** [comment]
I haven't played with this much, so this is theoretical, but things like `format` are by default an annotation in OAS 3.1. Also the equivalent schemas `{}` and `true`, and `{ not: {} }`and `false`could be taken into account.

**Comment by acunniffe** [comment]
Yeah - I mean that brings up an important philosophical question about what the library is calculation. 

Is a schema close if
- it has the same structure of assertions (cares about allOf, oneOf, anyOf). --- this one feels least useful. 
- if it will validate the same JSON as correct (optimizing for few false positives) --- this is what we are shooting for today
- if it will validate the same JSON as incorrect (optimizing for few false negatives) --- this is important, but probably hard without also giving it example traffic. Schema <> Schema doesn't encode enough data

**Comment by MikeRalphson** [comment]
Happy to close if this is out-of-scope.
