### ISSUE TITLE
Error: ENOENT: no such file or directory, scandir

### ISSUE THREAD

**Issue by mikewagnercmp** [opticdev/optic#1778]
**Describe the bug**
Following the getting started guide and installed optic on my mac. 

Trusted the TLS cert since it is a HTTPS site..

Attempted to run a capture using command optic capture qa2dify.yml https://<redacted>

immediately throws the following error:
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: ENOENT: no such file or directory, scandir '/var/folders/51/9nlfyfp55xd00nfqwzcbyf8m0000gn/T/optic/captures/bfefca12121f91c37a0a2b16a373a87e

doing some light googling turned up rebuilding node-sass which did not help. 

**Expected behavior**
Based on the getting started guide I expected to begin capturing traffic in a .yml doc.

**Details (please complete the following information):**
 - OS and version: MacOS 12.2
 - Optic version: 0.41.3
 - NodeJS version:19.6

**Additional context**

**Comment by acunniffe** [comment]
Hey @mikewagnercmp -- thanks for giving the tool a try. It looks like this issue has something to do with permissions. Optic tries to save captured traffic in that os's `tmp` folder. 

Can you open the Node REPL, get the tmp dir and then check it's permissions? 
```bash
$ node
 > require('os').tmpdir()
```

```bash
ls -l <tmp dir from above step> 
```

^^ share the result. 

Should be something that's easy to fix. Sorry you ran into this. We should be able to make errors better in the future if anyone else runs into this

**Comment by mikewagnercmp** [comment]
Looks like this - 

Welcome to Node.js v19.6.0.
Type ".help" for more information.
> require('os').tmpdir()
'/var/folders/51/9nlfyfp55xd00nfqwzcbyf8m0000gn/T'
> ls -l /var/folders/51/9nlfyfp55xd00nfqwzcbyf8m0000gn/T
ls -l /var/folders/51/9nlfyfp55xd00nfqwzcbyf8m0000gn/T
       ^^^

Uncaught SyntaxError: Unexpected token 'var'

**Comment by acunniffe** [comment]
You'll have to leave the node shell and return to bash to test this properly. 

`ls` is not a global node function. 

Sorry for the confusion. I asked you to run commands in two different kinds of shells 🙃

**Comment by mikewagnercmp** [comment]
That worked! I didn't try creating the file I guess that is pretty obvious after the fact, but i created an empty file and passe it in and it worked. I assumed the file woud have been created if not specified - I? was literally just going off the getting started guide 

https://www.useoptic.com/docs/oas-reference/client-guides

Extra error message there sounds like a good idea though. Thank you for helping resolve this.

**Comment by niclim** [comment]
> I assumed the file woud have been created if not specified

It doesn't currently do that, but I don't see why we shouldn't! I'll put an update up to do this, since there's no reason we shouldn't create a file - thanks!

**Comment by mikewagnercmp** [comment]
Awesome I will close this issue, I am of course running into something else with the certificate and HSTS - The cert is installed and trusted but optic is still erroring out. I'll open up a new issue for that one.
