### ISSUE TITLE
Untracked `openapi.json` is considered as uncommitted

### ISSUE THREAD

**Issue by Manouchehri** [opticdev/optic#1865]
**Describe the bug**

When running commands that specifically define which file to use (e.g. `openapi.yaml`), having an untracked file (e.g. `openapi.json`) will cause Optic to bail out thinking it's uncommitted.

```
dave@mbp corellium-openapi % optic verify openapi.yaml --upload
optic oas verify --upload can only be run in a git repository without uncommitted changes. That ensures reports are properly tagged.
dave@mbp corellium-openapi % git status
On branch main
Your branch is up to date with 'origin/main'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	notes.1.txt
	openapi.json

nothing added to commit but untracked files present (use "git add" to track)
```

**Additional context**
Because we're specifically _not_ using `openapi.json` in my example above, I don't think it's correct to tell the user there's uncommitted changes (which would imply `openapi.yaml` has uncommitted changes).

It might not be a bad idea to warn the user if they've accidentally put both `openapi.yaml` and `openapi.json` in the same directory though.

**Comment by niclim** [comment]
Hi - I have a fix up here https://github.com/opticdev/optic/pull/1868 which will check uncommitted changes for files relevant to the command being run.

This will also include any `$ref` links from your openapi.yml -> other local openapi yaml files.

I'll update here when I release a new version

**Comment by niclim** [comment]
`0.42.14` was just released which includes the fix above
