### ISSUE TITLE
Force upload with uncommitted files / runtime generated `openapi.yaml`?

### ISSUE THREAD

**Issue by Manouchehri** [opticdev/optic#1886]
**Describe the bug**
We generate our `openapi-en.yaml` file at runtime (but still want to track the changes in Optic), and we intentionally have the following in our `.gitignore`:

```
# OpenAPI generated files
openapi*.yaml
openapi*.json
```

**Expected behavior**
We still want to be able to use Optic to track API changes. I want Optic to use the commit hash of the current branch as the version. =) 

**Screenshots**
```
Run opticdev/action@v1
Installing optic
/opt/hostedtoolcache/node/18.1[6](https://github.com/aimoda/removed-api/actions/runs/removed/jobs/removed#step:7:7).0/x64/bin/npm install --location=global @useoptic/optic
npm WARN deprecated express-graphql@0.11.0: This package is no longer maintained. We recommend using `graphql-http` instead. Please consult the migration document https://github.com/graphql/graphql-http#migrating-express-grpahql.

added 581 packages in 15s

8[7](https://github.com/aimoda/removed-api/actions/runs/removed/jobs/removed#step:7:8) packages are looking for funding
  run `npm fund` for details
/usr/bin/git fetch --deepen=1
From https://github.com/aimoda/removed-api
 * [new branch]      1-add-removed-endpoints -> origin/1-add-removed-endpoints
 * [new branch]      1-add-removed-endpoints-david -> origin/1-add-removed-endpoints-david
 * [new branch]      1-removed-endpoints-optic-1 -> origin/1-add-removed-endpoints-optic-1
 * [new branch]      2-set-project-up -> origin/2-set-project-up
 * [new branch]      main             -> origin/main
Running Optic diff-all
/opt/hostedtoolcache/node/1[8](https://github.com/aimoda/removed-api/actions/runs/removed/jobs/removed#step:7:9).[16](https://github.com/aimoda/removed-api/actions/runs/removed/jobs/removed#step:7:17).0/x64/bin/optic diff-all --compare-from HEAD~1 --check --upload --head-tag gitbranch:1-add-removed-endpoints-optic-2
No comparisons were run between specs - `optic diff-all` will run comparisons on any spec that has an `x-optic-url` key
Get started by running `optic api add` and making a change to an API spec
```

**Additional context**
Related to #1865 and #1868.

**Comment by niclim** [comment]
Hi - I'm actually working on something for this right now for generated specs https://github.com/opticdev/optic/pull/1883

The idea is that you'll be able to run `optic diff-all --generated --compare-from cloud:gitbranch:main` after your generation script which will:
- automatically add / use specs without x-optic-urls (deduped by the githost + path)
- bypass the `uncommitted changes` check.
- compare against a spec hosted in optic cloud (i.e. something that isn't tracked against git)

All of this together would look something like `optic diff-all --generated --compare-from cloud:gitbranch:main` (optionally add `--match **/files` if you have multiple OpenAPI specs in your repo you don't want added.

Would this work for you?

**Comment by Manouchehri** [comment]
Ah yep, that'd work, thanks!

**Comment by Manouchehri** [comment]
> I noticed you are using the github action, in which case you can set:

I ended up not using it as the GitHub Action for Optic didn't seem to have an easy way to add `optic capture` into the workflow.
