### ISSUE TITLE
Verbose changelogs in GitHub PR comment?

### ISSUE THREAD

**Issue by Manouchehri** [opticdev/optic#1887]
**Describe the enhancement**
Instead of just `7 operations added`, it'd be nice if those 7 new operations were listed right in the GitHub PR comment. =) 

<img width="735" alt="image" src="https://user-images.githubusercontent.com/7232674/234999128-05856d8f-1eb8-4c7c-b76b-0904e6bfa67d.png">

**Comment by niclim** [comment]
Hi - this is now in `0.47.3` - you can now call `optic ci comment --verbose`  and it will render the operations added / changed / removed in the operation changed box (see sample comment here: https://github.com/opticdev/optic/pull/2030#issuecomment-1604369847)
