### ISSUE TITLE
Spectral logging included in `spectral` rulesets

### ISSUE THREAD

**Issue by acunniffe** [opticdev/optic#1943]
**Describe the bug**
After fixing some issues in my API spec that spectral told me about, I began getting this output to my console. I'm not sure why it's being passes through to stdout, but it's confusing. I was in "fix things" mode and was jarred by this error I wasn't able to address 

![image](https://github.com/opticdev/optic/assets/5900338/b53a75a5-bf03-4661-b786-dc0e17651e8b)

**Comment by niclim** [comment]
think this is fixed in https://github.com/opticdev/optic/pull/2267
