### ISSUE TITLE
query parameters in get requests

### ISSUE THREAD

**Issue by sidtagirisa** [opticdev/optic#204]
While I have been testing this library, I have noticed that query parameters in the get requests are not being captured.

**Comment by LouManglass** [comment]
@setshaft Hi! We're looking in to how best to handle query parameters. Do you have some examples you can share from your work, so we can make sure we consider your use case?

**Comment by setshaft** [comment]
@LouManglass I can think of three different scenarios right away. 

1. http://localhost:3000/api/some-url?key=value&key=different-value
2. http://localhost:3000/api/some-url?key=value
3. http://localhost:3000/api/some-url?key1=value1&key2=value2 

I think the three common scenarios that we see in GET requests are these. Please addon if I missed any commonly used scenario. If the library supports these scenarios, it will be good start with.

Thanks :)

**Comment by LouManglass** [comment]
@setshaft This is great, we're definitely looking at scenarios like this. Thanks.

To clarify - if you give several values for a given key (see example 1), would you expect them to be all of the same data type? For example, would you always expect strings, or could one value be interpreted as a string, another an integer, another a boolean...I expect the former, if they're varying data types any additional information on how this endpoint would work would be helpful.

Also, does the key take multiple values, or does one end up "winning" and becoming the captured value?

**Comment by setshaft** [comment]
@LouManglass Those were more generic examples which are commonly used in the real world. 
We don't see the 1st example in our work daily. We encounter only the 2nd and 3rd example. 

But for 1st example, we can assume them to be all of the same data type according to the real-world usage I have seen till now. 
While most modern frameworks give them as an array for values when we access that key from the query parameter. So, there are no winning values. While writing the swagger doc we can document key as data_type[].

**Comment by LouManglass** [comment]
Good to know. I want to be sure that we're covering the examples you're using currently first, since you've taken the time to reach out, and we appreciate the generic examples overall. I agree, they're common, and high on our list as well. I'll let you know what comes of our investigation, and keep you updated with any significant progress.

**Comment by setshaft** [comment]
@LouManglass Thanks. Please keep posted when this is feat is going to launch. :)

**Comment by klinskyc** [comment]
@LouManglass Thanks for your work on Optic. What is the latest thinking here? Our API uses query params heavily, and this is a large blocker for us to use Optic

**Comment by LouManglass** [comment]
Hi @klinskyc,

You're welcome, thanks for the kind words! We've shifted focus a bit to improve how we handle the initial batch learning of APIs from observed traffic. Feedback has shown us that a solid onboarding path is important to the value of Optic, and this work lies at the heart of the project. For now, we've had to push back query parameters.

I'm sorry we can't help you with this feature today. It's definitely on our radar to build on top of a fast, assistive platform. My suggestion would be to subscribe to the issue, as we'll be updating here once it's getting our developers' attention once again.

**Comment by solarmosaic-kflorence** [comment]
This is a problem for us as well. We can't fully rely on optic until query parameters (and ideally also headers) are supported.

**Comment by LouManglass** [comment]
@solarmosaic-kflorence We appreciate the feedback. Seeing the scope of the impact helps us prioritize the next problem to tackle. I understand you also need headers, is that a hard blocker like query parameters or could you rely on Optic with just query parameters, if headers were on a roadmap and you had some idea of what that looked like?

**Comment by solarmosaic-kflorence** [comment]
@LouManglass yeah I believe query parameters are more important. We can get away with documenting required headers for now, although not including those in optic would presumably mean if someone renamed a header, for example, we may not catch it during our build cycle. But I anticipate headers changing a lot less than query parameters, so I think it's acceptable to not have them covered for now.

**Comment by LouManglass** [comment]
@solarmosaic-kflorence That makes sense. Ideally we'd have everything for you right away, but practically we're going to have to prioritize between these and other tasks. Our goal is to get y'all walking so you can run, as the saying goes, and I hear that query parameters are going to be the most important part of that.

I don't have a roadmap for you right now, so subscribing to this issue is the best way to keep up to date with any progress or updates on query parameters. I know it's on our radar, and I'll be sure to share more when I have something concrete.

**Comment by ViRb3** [comment]
Added in v10.2.0: https://github.com/opticdev/optic/releases/tag/v10.2.0

Awesome job @LouManglass and team!

**Comment by sidtagirisa** [comment]
@ViRb3 Thanks for letting know. @LouManglass and Team thanks for adding the most awaited feature 😄 .

**Comment by LouManglass** [comment]
@ViRb3 @sidtagirisa Yes! We're really excited to get this out to everyone. Please give it a look, and let us know if you have any issues. If you have any other feedback, you're welcome to join us in the broader [community](https://www.useoptic.com/community) as well, which includes a Discord server. Enjoy!
