### ISSUE TITLE
Mac System Proxy settings not cleared once not closed properly

### ISSUE THREAD

**Issue by gilgardosh** [opticdev/optic#2040]
**Describe the bug**
After `capture` session, closing the terminal not by pressing `enter` leads to proxy still being set on system, resulting in no internet access

**To Reproduce**
1. run `optic capture ...` on a project
2. Close the terminal without properly terminating the optic execution (or put the Mac asleep)
3. Internet is not available

**Expected behavior**
Some failsafe that handles system settings  on any termination of `capture` execution

**Details (please complete the following information):**
 - OS and version: Mac OS 13.2.1
 - Optic version: v0.45.4
 - NodeJS version: 18.13.0

**Comment by notnmeyer** [comment]
hey @gilgardosh, thanks for the report! the transparent proxy mode has some rough edges like you noticed. depending on what you're trying to do, running a capture session in reverse-proxy mode might get you unstuck in the immediate, `optic capture --reverse-proxy...`.

reverse-proxy mode won't change the system proxy config, but requires that traffic is explicitly sent through the proxy (which defaults to `localhost:8000`).

**Comment by notnmeyer** [comment]
i should also mention, in the meantime when this happens you can turn off the system proxy from the command line (which saves you a trip your system prefs),

get the names for your network services,
```
$ networksetup -listallnetworkservices
Thunderbolt Ethernet Slot 0
Wi-Fi
Thunderbolt Bridge
```

turn off the web proxy for whichever network you're using,
```
# http
$ networksetup -setwebproxystate "Thunderbolt Ethernet Slot 0" off

# https
$ networksetup -setsecurewebproxystate "Thunderbolt Ethernet Slot 0" off

```

**Comment by acunniffe** [comment]
Hey @gilgardosh a lot of improvements have been shipped in https://www.useoptic.com/docs/capturing-traffic. We're phasing out the system proxy in favor of automated traffic sources (tests, postman, cyprus, etc).
