### ISSUE TITLE
Output of `optic diff` looks like a successful run, but it hides the errors that causes exit code 1

### ISSUE THREAD

**Issue by gabsong** [opticdev/optic#2135]
**Describe the bug**
I think this is a bug, but it may be open to interpretation. Running:
```sh
optic diff --base <branch> <file_to_compare_against> --check
```

Gave the following output:
```text
x Accounts API openapi/federation/external/swagger.2023-01.json
Preview docs:  https://useoptic.com/docs/cloud-get-started
Operations: 1 operation added
x  Checks: 36/48 passed (11 warnings)

specification details:
- /servers, /info/contact added
- /openapi, /info/version, /info/title changed

✔ POST /logistics/api/2023-01/accounts: added

  - request:
    - body application/json:
  - response 200:
    - body application/json:
  - response 401:
    - body application/json:
  - response 409:
    - body application/json:

...and 1 other endpoint

See the full history of this API by running "optic api add openapi/federation/external/swagger.2023-01.json --history-depth 0"
```

If I check the exit code, I get 1.
```sh
$ echo $?
1
```

**To Reproduce**
N/A

**Expected behavior**
I thought if there is an error causing the exit code 1, getting the output would be helpful. Or the exit code may be set on warnings? Because I do have warnings when running `optic lint`.

**Screenshots**
<img width="943" alt="image" src="https://github.com/opticdev/optic/assets/522076/e3c6f22d-7e78-49b9-9be4-1ff9f0f529f2">

**Details (please complete the following information):**
 - OS and version: Ubuntu (CircleCI virtual env)
 - Optic version: 0.47.3
 - NodeJS version: 18

**Additional context**
For context, there's no file to compare to in the staging branch. Also, ran `optic lint` to check for errors, but there were none. I think the exit code may be wrong, or the output is hiding the error.

**Comment by niclim** [comment]
Hi - it looks like the output isn't showing the errors - let me look into this.

If its possible, could you provide:
- the OpenAPI spec
- the ruleset you are using to run this (this is usually in your `optic.yml` file)

That'd be helpful to confirm should be rendered here

**Comment by gabsong** [comment]
Hi, I have more information and a clearer hypothesis for why this happened. It's a different run (meaning the spec has changed since), but I was able to obtain more information.

Here's the cli output:
```sh
$ npx optic diff ./openapi/federation/external/swagger.unstable.json --check --web

x Logistics API ./openapi/federation/external/swagger.unstable.json
Operations: 10 operations added
x  Checks: 192/297 passed (96 warnings)

specification details:
- /servers, /info/contact added
- /openapi, /info/version, /info/title changed

✔ POST /logistics/api/unstable/accounts: added

  - request:
    - body application/json:
  - response 200:
    - body application/json:
  - response 401:
    - body application/json:
  - response 409:
    - body application/json:

✔ GET /logistics/api/unstable/accounts/by_seller_id/{sellerId}: added

  - response 200:
    - body application/json:
  - response 401:
    - body application/json:
  - response 404:
    - body application/json:

✔ GET /logistics/api/unstable/accounts/by_seller_id/{sellerId}/is_seller_portal_account: added

  - response 200:
    - body application/json:
  - response 401:
    - body application/json:
  - response 404:
    - body application/json:

✔ GET /logistics/api/unstable/accounts/unified_seller_ids: added

  - query parameter startCreatedAt:
  - response 401:
    - body application/json:

✔ GET /logistics/api/unstable/accounts/unified_billing: added

  - query parameter startCreatedAt:
  - response 200:
    - body application/json:
  - response 401:
    - body application/json:

✔ GET /logistics/api/unstable/accounts/{logisticsAccountId}: added

  - response 200:
    - body application/json:
  - response 401:
    - body application/json:
  - response 404:
    - body application/json:

✔ GET /logistics/api/unstable/accounts/{logisticsAccountId}/seller_id: added

  - response 200:
    - body application/json:
  - response 401:
    - body application/json:
  - response 404:
    - body application/json:

✔ PUT /logistics/api/unstable/accounts/{logisticsAccountId}/is_test_account: added

  - request:
    - body application/json:
  - response 401:
    - body application/json:
  - response 404:
    - body application/json:

✔ PUT /logistics/api/unstable/accounts/{logisticsAccountId}/is_seller_portal_account: added

  - request:
    - body application/json:
  - response 401:
    - body application/json:
  - response 404:
    - body application/json:

✔ PUT /logistics/api/unstable/accounts/{logisticsAccountId}/status: added

  - request:
    - body application/json:
  - response 401:
    - body application/json:
  - response 404:
    - body application/json:

...and 10 other endpoints

See the full history of this API by running "optic api add openapi/federation/external/swagger.unstable.json --history-depth 0"
Opening up diff in web view

gsong@mbp in ~/project (staging●)
$ echo $?
1
```

Here's the [web output](https://app.useoptic.com/cli/diff#W7VLElHFWXRUlDMSthHVpOcBWh3whvQvesFgCUwZYIWwMlVhweDHCSt2j9W1xsNOQfHDxij3hLmp/GkENDj3Q6lm29Ls9dVwpRkTb9JfV1pqdwoG2asZVjCglObBeake6R4YDzm9xLcOS1dfRGQyZQn+Z+MlzzAaRaa91V0tazwqKyRSUa8onEBvT3fPhbwXPiWVsoKasLN7n5P/QvHlESoJBc6gUFF4jL9PyWH+r5xQrk7Q5H9Vye3h+dPuJHsgq8E4050Mt6yrA750jwnoAYijyUYVLwT274+lKyAljPrNke4A5vgyVL/mLun+7o0MWzzJIDEEplExZzoYOvA7iKJCUnfQboVaT5dSt3y7TaSYd+tGS7IyLUr/EPdRqZV7d3w+50Zs6l7ShEl85HnUMQk57UiDOFqXhE4hrOmtQhqsjFfKq/jRrThQEXIFfnS51saa77jQ7n0QJPBYCLl3Jl9qEzN0T/A39DPRoiJoJQJa+u7vKnbS7X8BfjFtTCBn0NhEhoSMEQg4N6dYKJHQ9q97hfslks465pp4WNMEgLPKmrrS7mbIniFrXIJ9Hk64W1oeXz7AFL9kOWNHlQMZFnoG6GxRFTG5L+9GhK+y7rf1PdY9slBPmKFDY9lZAaDOO0y6tGzTOZl0S+wgRVM7KhwNFo6rPCKnSZ7Sgvtmq0r8AvL1tTANaL1kkyBTMSQhWgM4ZT0tAi0z4qe4RKOwq16yj7TH/Tsori+3w+/ZjvSdbKOsm86ZTpzjqqG/txQMAXOoQbXmw/xWISZgtZDKIIoYnDUIUrtpd16tZbioAmfykDJ8NjGoOjYaF8vXI3OeuS/k3g3bvyWCAEkQ8/SQCDf1tKCILhS/zHDOvZT+SwzZRjzUzbQgx/VD1foSTCFoNFBdsp/6J/i5vhaI+Xird+8QqR/NdzNlDLO6K0/2d5TW4/Im1TJPyweCONZGn1GQ7V8PxEwLEQrwamSxAecktE0NAP9yRHIClSMsQiy80no/XBdjQMsqYOk4RUGpJfL9Wm0AJQjP0W6IJosfVRJdPsVWMRVxglwWWNLrhAqwHupn5Ep/zLDe/H9gYcB7eWd6AIqAkpJCvVbLq0VT5sOEYNXpPZbh8G9TLO/Ad+/+TcnX6ZlOP96F02EIiC3iVWMky95mk3GjMAXiv+RSdqFB7aRO0auUqQOhDpwSb2SjRgcMhmt2WQAQ3CXHrMuFlpjpCVEwQSocTf1mpi+FCHotmvZ50MjCyXE3ofSaIGisb5rcu+VgqKtSfXrJ+Jjv5qprmTL7AULeaaSkirxtuQACh5pTWf3KGSsbJvKHfsDxkOcFWemgzcLUMxVaLimqeHzcoK+AJMtIaIa9OqP1Np7eCtjk5wmCbFi9UtcvcdldVOYzRinj2NP/Uodu/yThIpxMmKgiZ1TmH9gEKreuF+PKVYuYnfoJ3imGiGnjYrtsLLi+ZTmlh5RA8Ax/veY68ypUKAlIwWgghniXa9m0IPv2tkBW2sVSDpJGKrrlwxif0P5Dq2FG0qbkuiKPAuqR3FDhhLH73zEgL647b7T76oyP2qhhWbU1CFlrpNG29FpI9mkIcurhG0mdGC0c9cpqpee6wZY7BN+FSs4ke4VtkilaObLkqeVRFx08qwl7qls0eUcSsEtSsuIQFsCvyQ4FV6JUaDzs3/yAecm0weuISJgUmYoyB3MqorHK/aOp02Us6OEMPDQCrSEwm+VBTVPghijDwSwrKMjR3iG7mY5R2WI1mizGUsv5fGqeHJVpAeN0T0WqdxdJSZtlb/OyCSyz6E5njdFSy5nhIgYo9vZZY8miGr3BOpsnRjdSQ6XqODUlXU3FkJMU+HDLBO0x3dNNTDV4Q968RFqJt8tqA+aNtv5DeW/9+XT4iAtFAYAs0npI806UkZudGb0o+YqYBWo/Qf0WtoFCzmNsKhJ26LExU2UldZXGHEdpxUZhngSrwYJ5hJZqLA5msEM+xKItl6DNULkN68ulbx4VOPtg+npmUW1nJpjjYZHfacmcMubq430tUnrmvDz9TKzCqH+x0shlT+QbhlUcrOeql0NREbqpcW+lZRf9qJRRu0vvjjgzL9RknfsV5UFJ9tmMLbcRsFbSVBqb0PSk6HfKaknA/PGTt7ZLjZEUlXfORZ+lrstZf71s5SLajxyDMEt1WTS6OVt+DpQIkysjes7yYiL4pOBkfJEX77JlP4PCHx51hN/9Q1puJiyTNr8CP73KSKfaKITEGEgQjf7xXRZgKw4FKWV9ndCDt4KCOPVLp11LYBFC7QuPB6gAFe/WQjMsQQ41jaP6Ja7L9J81UWo3mdNXxBCDcwOcwWngC4UgDcc84BM3vyZmWirjnZgrQRwjFQ2O5+oax2t5vdxPbDJgBtuSJpzt1wI5bdc8Z5x+qIYzvjRkdakDfBEpAOAY4UxsZY5wav5aVZHoa0YYV+5SRyICUzDYyeD6NhyLtRZ87kWXt5A19StccxmOUNXg46+uxXnnlZXNOq5gi6ycXOljjeVTKC33MCo3gkWaxL0q3eHoLWda9//qruyeLXfqesY2/xI1AFkzVev6w+yL8XQg69LFYexRdS2waNc5zb4Y3JVP/eeceSVUb6B2Cq6NYnmQi+7J5fvi/uetZ3oaOhL9P2dZvXTu1NWYpM562IPsQtV5pXjB7tGxjm7rXQ5PVowqo7o+1DPUvYXHd6Fu04WG10J9vxac25U2TG/iftzAaFcve3e2941OnY/TnMeNY0eBbMAL8x4vV6oc5Yl+G4XLtLFB4j6aPtSJNONt1ofhPszf+i3wbfrD/bHrf0RH6u1mbF7zY3Mpj81f5bG5RPLYZWPjX3jJ2FxqbK1rGpu88oi2Z/EZF+362D9PRIvVOquhNVbGJtA1tXJT/Zla2kT0YuCOERq45S/WwcjmEHzEWRJPTy14j40PEue8tJTbxSHf+GTGiRqUpTWIkBJ6Lj3h6M+hcz+MIeXwWlo4ctTUBK27+636Tfg0q8qh6pSYAp9yDkSnSaUD8Nup6EdVBnzA0Uv2bSCmHiaEO8l2NABb88EDgXaIeohtxCHv0c10wlStJ8MTpzhdHaJhtQVAfUA4gQ9RBqaYFIuYalsDZiF9FSNWm3d/bC7HB6g80AjrmzL8uGMR4JQRkipDfcKE91QFd/QXY/w5Cccf195eZLYuJERp/TQLkYcl4d1ER0VA0zCBoxURd7m0NazHAlwof2goVem5a8UxvU0vUoho8dEfpT/9uqlqeZFVYsLb11m1NqMPwAOPfAoBPnDgSOK7x8GQpsFpv1U3XrYqOvZj1hukdRZHLREpL2WSv+MNGFvT1hRWh6ImzI/xyEvFLhnPEIUYLHPx4e/FkuGfcPI3cab/dD8vJ6SYOVQH0unFp0PJdKmMVRG/9wrgnF6ukkorbxWPB74Y625mkpDOd+bPk9zYtPLugFeS2F90UEYz+0lHJtRIVsnHuBrJIZmYXUzUXP4G2fSfUptqeZU0MnK6rYuEn9tBeo84X1iYN4SH5ODTjPi36WljsloLkFxtrqUBP67t48s5x48eAogWYARe3v/krWWYoOI+76i3JT2uW5hhmrZShqzgndcjTJyVkAeQYK4XGz9hBQ0bnn+R3fK6N2H7sHuktz8rATG2APkjehTZxxf+9rTXv6z64iiqY3G0dbM4H2q2SBJkRVjPDrhuFueDYBZnQMUXR7CIC384+bf+yr1jpLt6QVXeGEFttPqKUZdMi6+YGUpp7RXzQBEtvYglkvy1DvRXFuFbZwUEwRRDBucU0IWRHzeFAXrJnztgvngdFzkkCGX2AcBfmeGvKIa+Z0+DSXcom7rorqzutWVfQr7TO9tu7fhOX3R5woLq3SQeD0jqKvga3IXsukGPyswjFhRZW88BVkVx7ixsEIvrqFm4oxx1MmGKQpTKDHwxpLzdA6lkvjsTlvPMowBDK2vun0c+YrC4EH1NmF6ItHJsMOSHoIwxZJOOrDLkjl7MMzbqEv/cUcRWNwYbckNTlpv1Z5hFPkqw0wxrIRSGGa5yKQMz9FVU9GVMEU+Jl/FCJAVdBFQY6raTIblosRb/2n7/yXv0XZbadvHTaJkE0y+QWnwWBgIdJE0AlI3M8cfvB8UhmBFGqwsk/vLIH1n+kpq7/qutJObIFVjS3GVGkZcYtjIrfrllUl35y7HTgBBCs6x6yyPCqALRTCrDlltAczAFkHwndl795RVRVYPgWk541cSUBYaN9LO5sJk0ZMU9yI2k33xag5GPda+Tr9eOFtj44KPDZTPqFhuz1PDTJ/mlzY5PC3ibU9o20rIQVjQiDxXj6PBvuEAd0sgf8b4fUvrqRDL/wskc4bIghdQXHMEyKdSRUv7oB4Pj4QJ7QCJdvENYI3VxVTiPhBGC4vMJalrndrqcjEN5BY8AxoIqdQ5ZD1DHGSGm6u/lYqlSR4k4/4nvD/8JFG3+Eyj6/CckvOW97hecX1fcQf/yGLW2UP+WjVnmglTJbdBFLTNANVReHzSYNinxpJgV2w1FOKdRT/MjjI0+PEHGQvuQxsYgpipj4d1QR45GPDlUWhvqf9JeJ9GBv4exY73+ceXoR6+WBG9TPcdbSCcTh15Isb7+H7TgBZXVhXA+Eg4qrAumzY3AM5XWBqtNL8CLVV4b4vlcvv5VVhPqXo9yxZdVXLq8Y4XSNb8bHOIY2hvCGPob0hgaHOIYWhwCGf7H2WYNkd//4u93754ivnUy7t8zE8DKGpQ66m+Qq6e/5Y5m83U+uKWb8TFJQf5pZplNYVxFg1vAkY09aVyVg1/FkZVJampZE7d8omGNXvN1XLh1m9Bh1g9FB+TO8rkX0snWJ7OQYtU6N9xqiYQ54eAkHMTCHNPiem4TDXesFu5zxyLiTjy4y+vVqWtQA6xjBLAJQKSKoQgA3f3pHFKCviEjaBxCgs4hJegdcoJWGF1D7fZ+hlzhw9Eze7kjC/W2RIGMK+sFhlTMgdEL1S90/xPAY0Qt8YN2R4LouRY+EhIO4ueaqcvjiImgbVZ9JEdiUeSPNG4xgE2680xeeaEsyWLoRobUzI1uaSYQHyQC4UEkkB5kAvFBKhAgNMmImrYXzyfjO9gpqd+t7bXUW9W+2UaBzWv19ZOb1+hmvsH7W8fIOETSefcuCg7gveMS6UEdcVDxfQlHJuGg8vtiarMTmwgYY9XmJo5FgTAC+Kl22uxQZwSSLwY5iwFvhqh1sm7K8963QHrMz4Jhpmexl9yt1D+Cs/sf3K/C374atIoOcA+K28g1vdM6aNmmbEySr+4ukv1aZJy5Tu86C/k65cJ6Jah8wLYV5bLfZ6kBEpI8SrBByZOgRGtKtpgSrim5YpVwYyVLohKsPEq2SKPEm5VgM0F9E3U75k/6DfaheOY0CB6Gh1NAJWrZRMIcsWYL75g1m3FxSLrX30I3jyaO44PUMCs3MgFMvI+zM/9EfoydrZskSshBFKwJE38U83VCBfiKIQBvb/fMC+kU6mNZSLHK38Yskwg4Ew5NwkEMnDF5sphNFKyx8mgxxyJhTTy0ywvVpmsfA3jodtxlAsRSYdQ8cTema4gIeoaAoGlICLqGiKBvCAnaYIjNr/F1McB6aJv7G3JC/jg267UjEoN3pOB1royfAH4WRvUelOIHcfEonJ+Eg8h4ZOoZ4JvYmGTVWcCPxcekeH6XV09cLFJOrhH+LDrsmUgO9u5WABAWtA9RQf+QFQQAYUEEEBd0xDZr/H3tzetfqpL3bDPKtccJc9dubLBhULvptOeIcW1bbGLUz81Is2yOscEHgG/23i7PoZ57APtpr4UB8NZiKvmg14QgRk6FT4GEgyg5ZeqWm2DiZJVVB92EWKyYI4CPF2APJPmkopykLuQixZ+5pHGgOxcDRAYhQGCQAiQGMUBkEASEBn0x0kbk+MQd+FzKY6nRfMsUyt0Zc6hsvbf5J2nEwpjnQDylxfV7ggt7LoTvmh5JueWjBngSi3jKippl4eMg4SBulpmWGrhhIueZ1VIEN2LR8yye2eW15fd+gz5DRZTdxMavLqBYVnQv84DsIA1IDuKA6CAPyA4SgfSgQYbZYFVDDMr3rjLa5Gl/qrLer763rfei/5SMEChzBn0A+MNv7HE/0qk+s69bpQDwbAPq9iCTPYiIQeHwJBzExCBTX5rdRMUhq14yeywyDsXDu7xuIuKPZvKcwmdxAc84QoB3n7qHpKB3yAmah6Cge0gK+oesoB22Q8NuWL7ekUrj3Wc/R1/v3oLY96x7JsDfxiTv68h9dL9cX77ZGf7yLib/AjEJOfD6HupXcnOc6dFjHhv4rbP0tikPdhgw1xWWrMcTX+t37tNPW+sH7FR6Ctjg75VU782lhKekZvZ8ITiF5wE=).

The web has more information that was not visible on the cli, but since this runs in CI we did not know what was going on and thought it was failing silently.

Looks like execution is exiting with an error due to violations of rules in spectral "added.yml". I can see the red errors in the web, which were not shown in the terminal.

**Comment by gabsong** [comment]
Unrelated question, but is it possible to also show the full URL of the web output in the cli text when using the option `--web`?

**Comment by acunniffe** [comment]
Thanks @gabsong - the web output should give us what we need to debug this properly. We'll get the CLI output fixed. 

Re: 
> is it possible to also output the web URL in the cli when using the option --web

Currently we don't upload any data to Optic's servers when you use `--web`. The data is kept in the URL fragment which is good for privacy, but bad for portability because the URLs end up so long. 

If you want to see the changelog + docs links in CI, you can use the `--upload` flag ([see example](https://github.com/opticdev/bookstore-api/pull/2))

Is setting that up something you're interested in?

**Comment by gabsong** [comment]
> If you want to see the changelog + docs links in CI, you can use the `--upload` flag ([see example](https://github.com/opticdev/bookstore-api/pull/2)). That prints shorter URLs to the CI logs, and (optionally) comments them to the PR feed. Is that something you're interested in?

Thanks Aidan! I can look at the `--upload` flag. Will probably know more after I try it! Is the example link correct? I get another perhaps unrelated PR.

**Comment by acunniffe** [comment]
Great. Let us know if you need help setting it up. 

It requires a token from Optic Cloud. Explained here: https://www.useoptic.com/docs/cloud-get-started#3-turn-on-cloud

The example I sent was just to show you what it looks like after you upload. It's from an example repo we use during demos.

**Comment by gabsong** [comment]
I see, will take a look :)

**Comment by niclim** [comment]
Hi @gabsong - I released a new version `0.47.16` that I think should fix the issue of missing errors - could you take a look and confirm whether the new version fixes the issue you are seeing?

**Comment by niclim** [comment]
Going to close this out first since I believe this fixes the issue, but if this doesn't fix the problem please feel free to reopen the issue - thanks!

**Comment by gabsong** [comment]
Sorry for my delay responding, it did fix the problem! Thank you so much 🙂
