### ISSUE TITLE
API sessions have invalid file names on windows

### ISSUE THREAD

**Issue by acunniffe** [opticdev/optic#22]
**Describe the bug**
The Optic API session naming convention used today is not compatible with most versions of windows. [Naming a file or directory](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#file-and-directory-names)

**To Reproduce**
Run API Start on Windows
Cancel API Start
Run API Spec 
`Error: ENOENT: no such file or directory, open 'D:/Learning/optic/server-example/.api/sessions/2019-09-09T09:40:31.725Z-2019-09-09T09:40:53.179Z.optic_session.json' `

**Expected behavior**
API Sessions save and load properly.

**Comment by acunniffe** [comment]
Fixed in 9b16b28

**Comment by khainx127** [comment]
Thanks, this fix worked for me
