### ISSUE TITLE
openapi spec path is not normalized to posix-compatible representation in optic.yml

### ISSUE THREAD

**Issue by juliangrube1988** [opticdev/optic#2258]
**Describe the bug**
The path to the openapi specification is not normalized.  A path that works on a windows system doesn't work for a linux machine.

**To Reproduce**
1. Start Windows
2. Create optic.yml: `optic capture init openapi/api.json`
3. Path in Optic.yml: `[PARENT_FOLDER]\openapi\api.json`
4. Start Linux
5. Create optic.yml: `optic capture init openapi/api.json`
6. Path in Optic.yml: `[PARENT_FOLDER]/openapi/api.json`

**Expected behavior**
Path to openapi file should should be normalized so that it works for both: windows and linux.

**Details (please complete the following information):**
- Debian 11.7, Windows 11
- Optic: 0.49.3
- NodeJS version: 18.14.0

**Comment by notnmeyer** [comment]
i think the correct thing is to actually use posix-compatible paths. MacOS and Linux are already doing the correct thing, and Windows supports both `windows\style` and `posix/style` paths already.

one of the mistakes we're making internally is not treating paths as posix and using node's default platform-specific path handling.

for example, given a capture config like,

```
capture:
  test/openapi.yml:
  ...
```

and then running capture on windows with that same path, we get this,

```
PS C:\Users\nate\code\openapi-gen-go-gin> optic capture test/openapi.yml
Expected a capture config entry for test\openapi.yml. To add a capture config entry to your optic.yml, run 'optic capture init test/openapi.yml'.
```

as we can see when we parse the path on windows it comes out as "test\openapi.yml".

this is a bit different from intentionally support windows style paths in optic.yml though. id _still_ advocate for `capture init` to write posix-compat paths in that scenario.

so in my mind the question is what we should do if a user puts a window style path in their optic.yml? should we silently accept it? complain about it and ask them to change it? automatically convert it to posix?

**Comment by notnmeyer** [comment]
[v0.49.6](https://github.com/opticdev/optic/releases/tag/v0.49.6) has been released with a fix.
