### ISSUE TITLE
`optic run` Misleading logs

### ISSUE THREAD

**Issue by Alexandre-Herve** [opticdev/optic#2269]
Optic run: Any YAML syntax error or OpenAPI validation issue will cause this error

![Screenshot 2023-09-05 at 1 09 48 PM](https://github.com/opticdev/optic/assets/2964863/62c6f65b-6d95-4528-bf9d-dacf650214fd)

**Comment by Alexandre-Herve** [comment]
@acunniffe could you give me a bit more details about the context, in particular did you happen to run this from a git repository without a remote origin set?

**Comment by Alexandre-Herve** [comment]
Improved the error message:
<img width="1182" alt="image" src="https://github.com/opticdev/optic/assets/2964863/065e81c5-88f5-4fa1-af0a-b8011d5510cf">

**Comment by Alexandre-Herve** [comment]
(added the missing "by" in "by their path")

**Comment by acunniffe** [comment]
Hmm. I can't get it to show up anymore. Now I remove all remotes this happens:
<img width="1001" alt="Screenshot 2023-09-07 at 9 01 36 AM" src="https://github.com/opticdev/optic/assets/5900338/76afe548-bfa7-42a6-a16c-2a6b569209d3">

**Comment by Alexandre-Herve** [comment]
ah, do you have at least one commit or not?
