### ISSUE TITLE
Express Optic 

### ISSUE THREAD

**Issue by Pra3t0r5** [opticdev/optic#228]
So, i'm working on an API that will scale a lot over time, and when i was looking for a good OAs3 autodocumenting solution on SO, i stumbled with Optic.

I followed the install and setup guides and ended up with the next setup:

1. `optic.yaml` which initially had the suggested `port: 4000`, however i later changed it to `port: 3300` since it was the one that Optic was trying to use, also take note on the `command` (more on that in **3.**):
![Screenshot from 2020-06-28 21-55-39](https://user-images.githubusercontent.com/38087682/85963485-515f9500-b98c-11ea-8d7b-5538a3c91c77.png)

2. `bin/www` entry point, which differs from the examples in the guides, thus i tried different combinations with `app` and `server` objects:
![Screenshot from 2020-06-28 21-55-27](https://user-images.githubusercontent.com/38087682/85963486-51f82b80-b98c-11ea-9bae-07aaeab7241f.png)

3. And since this project is handled by PM2, note the `npm run pm2` definition, it uses the `PM2 Ecosystem Configuration File` (see **4.**):
![Screenshot from 2020-06-28 21-55-50](https://user-images.githubusercontent.com/38087682/85963484-50c6fe80-b98c-11ea-83c3-fbf88dc786c3.png)

4. Said file is just an autodocumented and easier to handle way to launch `PM2 Processes`, as far i understood `Optic` should end up intercepting/wrapping the app, which in time gets wrapped by `PM2`, however there might be a conflict around that matter:
![Screenshot from 2020-06-28 21-55-58](https://user-images.githubusercontent.com/38087682/85963483-50c6fe80-b98c-11ea-905a-f8e71ffb72df.png)

These are the errors that i could not work around,  no matter how i handle `bin/www` and `optic.yaml`:
![Screenshot from 2020-06-28 21-57-45](https://user-images.githubusercontent.com/38087682/85963480-4f95d180-b98c-11ea-9f7a-5c36d8cd7abb.png)
![Screenshot from 2020-06-28 21-57-25](https://user-images.githubusercontent.com/38087682/85963481-502e6800-b98c-11ea-8af4-fe3c91566edc.png)

I also tried just launching the `api check start` by using `node app.js` and `node bin/www` commands to completely avoid `PM2`, but the behavior remains.

I'm quite sure the problem is around **2.**...

**Comment by LouManglass** [comment]
Hi @Pra3t0r5,

Thanks for the detailed report!

The local Optic CLI acts as a proxy for your application traffic to observe requests to support the  autodocumenting solution you're looking for. Optic starts your application with the `command` configuration, and expects that application to start on localhost on the port defined by the `OPTIC_API_PORT` environment variable. From what I can see in the first `api check start` output, that seems to be running well.

Then, Optic starts on localhost on a different port to intercept and observe request traffic. This is defined by the `baseUrl` configuration, set here to port 4000. That part failed the first check. Is it possible there's already software running on port 4000? There's a few quick checks:

- See if you can identify an existing application bound to the port. Perhaps something from PM2 or another project is using that port. Instructions vary by platform, recent MacOS versions have a version of [lsof](https://stackoverflow.com/questions/4421633/who-is-listening-on-a-given-tcp-port-on-mac-os-x) for example.
- Try a different port. Change the `baseUrl` configuration to use an unlikely port (such as 38080) and see if the check passes.

If you're still having problems after ruling out port 4000 being in use, and if this is a publicly visible project, please let me know where it is. If I can try to reproduce the issue locally, that'll help as we work with you further on it.

**Comment by Pra3t0r5** [comment]
Hi @LouManglass !

Thank you very much for your attention!

I've checked the ports and you where right:
![Screenshot from 2020-06-29 14-28-30](https://user-images.githubusercontent.com/38087682/86037244-72b89380-ba15-11ea-805d-980c75332387.png)

There was a vscode extension occupying that port which i totally forgot i had. Therefore i tried the exact same setup, but this time changing the `baseUrl` port to exactly the one you pointed (`38080`), and the result was odd:
1. PM2 had no trouble starting the process:
![Screenshot from 2020-06-29 14-42-58](https://user-images.githubusercontent.com/38087682/86038168-e5763e80-ba16-11ea-86d3-b5a872f83ea6.png)
2. And my `api` was up and functional:
![Screenshot from 2020-06-29 14-29-49](https://user-images.githubusercontent.com/38087682/86037558-e9559100-ba15-11ea-95fe-ae14aa47d171.png)
3. But as soon as it did...
![Screenshot from 2020-06-29 14-37-01](https://user-images.githubusercontent.com/38087682/86037649-130eb800-ba16-11ea-8204-ca6c10da46c8.png)
4. ...Optics `api check start` failed:
![Screenshot from 2020-06-29 14-38-29](https://user-images.githubusercontent.com/38087682/86037736-3b96b200-ba16-11ea-80cd-54f55a705b68.png)
5. This time i checked and there is nothing running there:
![Screenshot from 2020-06-29 14-40-10](https://user-images.githubusercontent.com/38087682/86037949-87495b80-ba16-11ea-880f-3807ed0aadd5.png)

The project itself is private, but since the problem involves only the entry point i see no issue on extracting that part so you can test it on your own. 
Lemme do that, i will comment below with the link when ready!

**Comment by Pra3t0r5** [comment]
Hi again @LouManglass !

Here you go, the api entry point stripped from everything else:
[Pra3t0r5/api_rest_cruciclub_optic](https://github.com/Pra3t0r5/api_rest_cruciclub_optic.git)

**Comment by LouManglass** [comment]
Perfect, thanks! I'll take a look at this and get back to you in a bit.

**Comment by LouManglass** [comment]
@Pra3t0r5 The summary is, using `api`/Optic to run a command implies to Optic that it should watch the lifecycle of that command. This works great for applications that run directly (such as a `node bin/www`) but is a bad assumption when using tooling like pm2. As I understand it the `pm2` invocation to spin up services is designed to be short-lived (it triggers other tasks and then quits, letting the background daemon do continuing work). Optic gets confused and thinks the API application being observed is finished.

I issued a pull request against your example with a sample of a hidden Optic mode that works more like a transparent proxy. Instead of watching the process lifecycle, we provide a proxy that runs independent of the command. It's an undocumented feature as it's still under active development, and the PR should give you more information on how it works.

Please note that we're actively working on this feature currently, and it's subject to change (mostly around configuration, to make it clearer). Going forward, I think that the best integration would be to consider how Optic would live as a module/app within the pm2 ecosystem. We're not quite there yet, and I'd like to leave this open for further investigation in a few weeks when we have some more information on our side.

In the mean time, the PR on your sample repo worked for the single app example, and should work generally for your project. I'm happy to chat more if there's other hurdles, and would like to reach out again once we have this feature ready to integrate more directly into your workflow.

**Comment by Pra3t0r5** [comment]
@LouManglass Awesome! I will test the PR you issued in both the example repo and the main project, and get back to you with any useful feedback i get.
I will happily test on my project further developments in the matter too.
Thank you!

**Comment by LouManglass** [comment]
@Pra3t0r5 My apologies! I was just scrolling through my tabs and realized that I never actually sent the PR...it was sitting just waiting for a button click!

Full notes in the [PR](https://github.com/Pra3t0r5/api_rest_cruciclub_optic/pull/1) but at a high level, I created a new task `pm2` in `packages.json` which invokes a new Optic task `pm2-start`. This new task doesn't expect to run any commands, and instead acts as an always up proxy.

If you're seeing port contention on 38080 still, you might want to see if anything is running on that port with something similar to `lsof -iTCP -sTCP:Listen -P` and kill that process if it's not there intentionally.

**Comment by LouManglass** [comment]
@Pra3t0r5 Howdy, I'm pulling the conversation back into the issue here in case anyone needs to follow along in the future. Reference to notes and debugging info in https://github.com/Pra3t0r5/api_rest_cruciclub_optic/pull/1

I suspect there's additional environmental differences, as here's my output:

```
npm start pm2                                         
> crucijuegos-api-rest@0.0.0 start /Users/lou/repos/api_rest_cruciclub_optic
> npm run pm2 && pm2 flush && pm2 log api "pm2"


> crucijuegos-api-rest@0.0.0 pm2 /Users/lou/repos/api_rest_cruciclub_optic
> pm2 start pm2-env.config.js --only api-rest && api run pm2-start

[PM2] Applying action restartProcessId on app [api-rest](ids: [ 0 ])
[PM2] [api-rest](0) ✓
┌─────┬─────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name        │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼─────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0   │ api-rest    │ default     │ 0.0.0   │ fork    │ 44058    │ 0s     │ 345  │ online    │ 0%       │ 7.3mb    │ lou      │ enabled  │
└─────┴─────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
[optic] Review the API Diff at http://localhost:34444/apis/1/diffs
```
I notice you appear to be running Debian. Would you mind sharing your release version, such as in `/etc/os-release`? I can try to match your host as well, I reproduced this on MacOS Catalina (10.15.5). The two main differences in output that jumped out at me were:

- You have a debugger running, though I don't suspect that as a contributing issue currently, and
- you receive a exit 139, that implies to me a segmentation fault. I'd like to rule out differences in our host environment.

I appreciate your thoroughness and the time you're taking to help me understand this one!

**Comment by Pra3t0r5** [comment]
Hi again @LouManglass!
Pardon me, i absolutely forgot to share my environment specs! 
Indeed, i'm running Debian, here you go:
```bash
⟩ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
also, just in case:
```bash
⟩ uname -a
Linux debian 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux
```
```bash
⟩ node -v
v13.11.0
```
Yeah i got the debugger running which was an interesting thing to see. But silly me, at that moment couldn't find a way to detach it, hehehe. I do doubt too that the problem comes from there.
Also, totally missed that error 139!

**Comment by LouManglass** [comment]
@Pra3t0r5  Excellent, thanks! It's on my list to investigate a more faithful reproduction to your environment today and see where I get. I suspect this may involve a bit more digging in, and if you have some time for a call next week I'd be happy to get you a Calendly link or use your scheduling tool of choice. We might not need it in the end, though I'd like to put the option on the table now to plan ahead.

I'll follow up later when I have more to report.

**Comment by LouManglass** [comment]
@Pra3t0r5 It appears we've found the culprit: Optic supports both HTTP and HTTPS for local testing, to fully mock existing environments. A default in an underlying library that wasn't overridden meant we generated a certificate with a 1024 bit RSA key, which a Debian environment (understandably) doesn't like.

We're testing out a fix for the next release which assures the self-signed certificate chain is 2048 bit all the way through, which in my manual testing against your reproduction project (thanks for that!) resolves the issue. I can reach out once it goes live with some other fixes, or if you want I can suggest a quick patch to your current environment that won't break compatibility with upcoming versions.

Thanks again for all your time on this, it was very helpful!

**Comment by Pra3t0r5** [comment]
@LouManglass Awesome finding! And please, thanks to you for the superb support! 

I'm not really in a hurry yet, and since it's clearly noticeable that you guys are both very active and commited to this project, i don't mind waiting a bit for the next release!

I will be lurking around, please feel free to PM me if needed. Till the next time!
