### ISSUE TITLE
Docs link in readme is broken

### ISSUE THREAD

**Issue by chronark** [opticdev/optic#2357]
**Describe the bug**
This link in the readme leads nowhere
https://www.useoptic.com/docs/compare-openapi

**To Reproduce**
1. Go to readme
2. Click on the first docs link
4. See a 404 page

**Expected behavior**
to see actual docs

**Screenshots**
<img width="575" alt="CleanShot 2023-09-30 at 13 10 31@2x" src="https://github.com/opticdev/optic/assets/18246773/b1f42971-c903-4a6a-b0f8-3cb02535656a">

**Details (please complete the following information):**
- not applicaple

**Additional context**

**Comment by acunniffe** [comment]
Thanks @chronark -- we rewrote docs recently and missed that redirect. I've added one to our docs site so old links across the internet will go to the latest. 

Let me know if I can help with anything else.
