### ISSUE TITLE
OAPI 3.1 validation does not allow license identifier field

### ISSUE THREAD

**Issue by infinitestory** [opticdev/optic#2360]
**Describe the bug**
The [OpenAPI 3.1 spec](https://spec.openapis.org/oas/v3.1.0#fixed-fields-2) allows the `license` object to contain an `identifier` field.  Optic's validation step rejects this field.

**To Reproduce**
* Create any spec with a license that includes an identifier field.
* `optic run` or `optic diff` on that spec (if `diff`, use strict validation)
* Optic rejects the spec.

**Expected behavior**
Optic should allow the spec.

**Details (please complete the following information):**
 - OS and version: Linux
 - Optic version: v0.50.0
 - NodeJS version: 20.5.1

**Comment by niclim** [comment]
Thanks for the report - I've got a fix up here https://github.com/opticdev/optic/pull/2368 and will report back here once we've put out a new version

**Comment by yonilerner** [comment]
Thank you very much for the quick turnaround on this!
