### ISSUE TITLE
Improve the breaking changes rule regarding property types

### ISSUE THREAD

**Issue by infinitestory** [opticdev/optic#2372]
**Describe the enhancement**
Sorry for the vague title, I couldn't think of a concise explanation.  Right now, it seems that the breaking changes rule which validates whether a property's type has changed just checks whether the set of allowed types is identical from spec A -> spec B.  However, IMO this isn't entirely consistent with the definition of a breaking change.  For request properties, the set of allowed types should be able to strictly expand (i.e. spec B set of types is a superset of spec A), and for response properties, the set of allowed types should be able to strictly shrink (i.e. spec A set of types is a superset of spec B).  Under these constraints, any client capable of interfacing with api A will also function on api B.  So these should be permitted by the type checking rule, IMO.

I understand it may not be easy to change this behavior, as it might be considered a breaking change in optic itself.  If changing this behavior outright is impossible,
  1) is it possible to add this behavior as a customization option on the breaking changes ruleset?
  2) do you have any suggestions for how we could easily implement this customization ourselves?

**Comment by niclim** [comment]
Hi - this seems reasonable and consistent with the philosophy with our other breaking changes rules (i.e. request properties / keys can be expanded, response properties can be narrowed), it just seems to have been implemented differently for these rules.

I'm working on a PR now to update the behavior.

----

That aside, for any other rules / suggestions you have in the future there's two options:
- we're more than happy to discuss what else you think should be included in our rulesets (breaking changes or other) and also happy to accept PRs
- you can write your own custom rules for your specific use case ([docs here](https://www.useoptic.com/docs/standards/writing-custom-rules)) - if you do decide to write your own custom rules, feel free to [schedule a call with us](https://www.useoptic.com/book-demo) and we can help you out here

**Comment by niclim** [comment]
Version `0.50.7` includes these updates. In particular, these following cases are now allowed
- A request parameter's type is expanded (e.g. `type: string` -> `type: [string, number]`)
- A request body property's type is expanded (e.g. `type: string` -> `type: [string, number]`)
- A response body property's type is narrowed (e.g. `type: [string, number]` ->  `type: string`)

Thanks for the report and let us know if there's anything else we can do to help!

**Comment by infinitestory** [comment]
> Version `0.50.7` includes these updates. In particular, these following cases are now allowed
> 
>     * A request parameter's type is expanded (e.g. `type: string` -> `type: [string, number]`)
> 
>     * A request body property's type is expanded (e.g. `type: string` -> `type: [string, number]`)
> 
>     * A response body property's type is narrowed (e.g. `type: [string, number]` ->  `type: string`)
> 
> 
> Thanks for the report and let us know if there's anything else we can do to help!

Hi!  Thanks for the speedy response and fix!  I've checked out v0.50.7 and it indeed fixes the issue in most cases, but there is one case I found where it doesn't seem to work correctly.  When either the before or after property is a `oneOf`, the type is treated as the empty set.  This causes the expansion/narrowing checks to work in the wrong direction in general, resulting in both false positives and false negatives.

**Comment by niclim** [comment]
Ah yes, that is an issue, thanks for reporting.

I think we'd need to think more about how we would implement this. Handling `oneOf` and `anyOf` is a little more complicated to detect breaking changes since we can't just use a set difference to figure out if something is narrowed if there's an `object` as one of the variants in `oneOf`. I've created an [issue here](https://github.com/opticdev/optic/issues/2387) to track this.
