### ISSUE TITLE
Feature: add authorization support for remote references

### ISSUE THREAD

**Issue by MitriSan** [opticdev/optic#2486]
**Describe the enhancement**
We are trying to organize some common models for our API repos. One of the possible solutions to do this is to use remote references via `$ref`. However, there is currently no way to safely use private repos in $ref, as we need to have a way to authorize access to remote repos without including login/pass in the remote URL itself.
**Additional information**
It would be very nice to configure this via optic.yml somehow, maybe set environment vars that should be used for auth when pulling remote references.

**Comment by notnmeyer** [comment]
you mentioned private repos—hosted where? is it GitHub.com, GitHub enterprise, GitLab, something else? do you have a sense for what you want to set specifically (bearer token on an authorization header, etc)?

we've been talking internally for a bit about templating optic.yml and/or adding .env/env var support for similar use cases. any details you can share about your specific needs would be very useful for us.

**Comment by notnmeyer** [comment]
cc @niclim
