### ISSUE TITLE
If any of the urls in the openapi spec match the url that is defined in optic.yml, optic breaks

### ISSUE THREAD

**Issue by mithodin** [opticdev/optic#2530]
**Describe the bug**
If in the servers block of the openapi spec, one of the entries matches the url in capture.<name>.server.url, optic capture no longer detects issues in the responses and reports a coverage of 0.0%.

**To Reproduce**
1. Check out the example repository https://github.com/mithodin/optic-path-repro
2. Run `npm run optic:test`. Optic reports 0.0% coverage
4. Edit spec.json and remove the url `http://localhost:3000/a` from the list of servers
5. Re-run `npm run optic:test`. Optic reports 100% coverage

**Expected behavior**
Optic should report coverage and detect mismatches independently of whether the server url in optic.yml matches any of the urls in the openapi spec.

**Comment by acunniffe** [comment]
Hey @mithodin -- this should now be fixed in `0.52.2`. let us know if it works for you

**Comment by mithodin** [comment]
Indeed, it works! Thank you for the very quick fix!
