### ISSUE TITLE
Replace deprecated analytics-node in @useoptic/optic

### ISSUE THREAD

**Issue by jgresty** [opticdev/optic#2557]
The package analytics-node has been deprecated, [see github repo for details](https://github.com/segmentio/analytics-node), and should be replaced with @segment/analytics-node.

This is raising flags in automated scanners since it transitively depends on a vulnerable version of axios.

**Comment by acunniffe** [comment]
Will take a look at this today. Looks like a drop-in replacement

**Comment by acunniffe** [comment]
This should be out in `0.53.5`
