### ISSUE TITLE
Docs: The command in generate a changelog is wrong

### ISSUE THREAD

**Issue by starlightknown** [opticdev/optic#2600]
**Describe the bug**

In the https://www.useoptic.com/docs/openapi-changelog page. 

`optic history openapilyml --history-depth=20`

here `openapilyml` needs to be `openapi.yml`

It throws an error - `path_to_spec` is not a valid specification file path`

**To Reproduce**
Run `optic history openapilyml --history-depth=20`

**Expected behavior**

**Screenshots**

**Details (please complete the following information):**
 - OS and version: [e.g. Mac OS 13.1]
 - Optic version: [e.g. v0.37.1]
 - NodeJS version: [e.g. 18.0.0]

**Additional context**

**Comment by acunniffe** [comment]
Fixed the typo! Thanks for finding this. Anything else we can do to help?

**Comment by starlightknown** [comment]
> Fixed the typo! Thanks for finding this. Anything else we can do to help?

Thank you, that's all
