### ISSUE TITLE
Trouble Installing optic 8.2.2 in Debian 10

### ISSUE THREAD

**Issue by Pra3t0r5** [opticdev/optic#263]
Howdy!

After noticing the new update i deleted Optic and installed the new version as your docs specify, but i've got this error:

![Screenshot from 2020-07-15 22-11-48](https://user-images.githubusercontent.com/38087682/87615158-71ab8580-c6e8-11ea-8888-1ec5868a1a02.png)

This are my system specs:
`Linux debian 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux`

And these are my development environment details:
```bash
~/Projects/node/api_rest_cruciclub_optic · (master±)
⟩ npm -v
6.14.6

~/Projects/node/api_rest_cruciclub_optic · (master±)
⟩ node -v
v13.11.0

~/Projects/node/api_rest_cruciclub_optic · (master±)
⟩ pm2 -v
4.4.0
```

Lastly, here are my project details, you can check them at [this repo](https://github.com/Pra3t0r5/api_rest_cruciclub_optic)
```json
{
  "name": "crucijuegos-api-rest",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "start": "npm run pm2 && pm2 flush && pm2 log api-rest",
    "pm2": "pm2 start pm2-env.config.js --only api-rest"
  },
  "dependencies": {
    "bcrypt": "^4.0.1",
    "cookie-parser": "^1.4.4",
    "cors": "^2.8.5",
    "debug": "~2.6.9",
    "ejs": "~2.5.7",
    "express": "~4.16.0",
    "helmet": "^3.15.1",
    "http-errors": "~1.6.2",
    "jsonwebtoken": "^8.5.0",
    "mercadopago": "^1.3.2",
    "morgan": "~1.9.0",
    "mysql2": "^1.6.5",
    "pm2": "^4.4.0",
    "sequelize": "^4.43.0",
    "twilio": "^3.48.0",
    "winston": "^3.2.1"
  }
}
```

**Comment by LouManglass** [comment]
I'm seeing the same thing. Thanks for the report, and sorry for the inconvenience! I've reproduced this on the latest update on both Debian and Mac, and we've got a good lead from the errors. We're digging into it.

**Comment by LouManglass** [comment]
This is resolved in the latest version, 8.2.3. Please run your update again, and the latest package should pull down. I've validated it on Debian as well, to be sure.

**Comment by Pra3t0r5** [comment]
Excellent, I could install and start documenting with Optic! 

However, on a small note, i've noticed an error that even if it seems to be trivial for my documentation process, you might find it helpful:
![Screenshot from 2020-07-19 02-21-00](https://user-images.githubusercontent.com/38087682/87882528-dad81500-c9d6-11ea-8513-595f89e20024.png)

Thank you very much!

**Comment by LouManglass** [comment]
You're very welcome! Permissions can be finicky across platforms, and it's something we're actively working on. Thanks for the report, and let us know if we can help out in any other way.
