### ISSUE TITLE
Question: Is it possible to run optic with app running on different server? 

### ISSUE THREAD

**Issue by ekaterinasmarp** [opticdev/optic#264]
Hello, 

I am interested in using optic in order to generate open api for the existing endpoints. 
I have an installation of my application in the cloud, and would like to run optic separately. The idea it that I do not use the port env variable inside my app, but rather tell optic which application (port, host) to proxy and then just use the optic host and generate traffic to it directly. 

Not sure if it is possible at all, could not find any documentation for this. 

Thanks a lot

**Comment by LouManglass** [comment]
Hi @ekaterinasmarp 

That is definitely possible, and something we want to fully support. Currently, it's a feature that's undocumented and under active development this cycle. I can let you know at the end of this cycle once the feature is fully ready and documented, or if you'd like, I can help you get set up with the current implementation. I can either send you some temporary instructions or jump on a call/chat to work with you to get it running.

Our current cycle ends next week, and if you have some time I'd recommend waiting for the full feature to be released. Let me know what's most helpful.

**Comment by ekaterinasmarp** [comment]
@LouManglass Thanks! We can definitely wait for the end of the cycle

**Comment by LouManglass** [comment]
@ekaterinasmarp That's good to hear, I'll reach out once we have something to show off and proper documentation.

**Comment by ViRb3** [comment]
Are there any updates on this use case? I would love to play around with Optic using an external API server. If this isn't officially supported yet and the existing workaround is not too complex, I would love to hear about it. Thanks!

**Comment by LouManglass** [comment]
Hey @ViRb3,

We're glad you found it, thanks for the kind words! We'll be making that more discoverable in the near future. It's still relatively new, and we'd be happy to hear of any issues or feedback you have. Feel free to reach out here, or if you want to chat a bit, I'll make some time to discuss any questions you have further. We appreciate you giving it a look!

**Comment by LouManglass** [comment]
@ekaterinasmarp We haven't officially released this feature yet, though I wanted to let you know there is preliminary documentation and it is fully functional: https://docs.useoptic.com/captures#transparent-proxy-task-mode. If you have any feedback or want to chat, let me know and I'll set aside some time.

**Comment by LouManglass** [comment]
With the latest version of Optic we've also released a companion integration tool at [app.useoptic.com](https://app.useoptic.com). It helps you get set up to use Optic with your current application. For running apps on remote servers, you'll select **Manually Configure Proxy** when choosing an integration mode. This will let you define where your application lives by URL, and sets up a local listener to observe and proxy traffic.

The integration tool is the easiest path to follow, though keep in mind it will overwrite any current Optic configurations you have. If you'd like to dig into the configurations manually, please check out our [Configuring Captures](https://www.useoptic.com/docs/faqs-and-troubleshooting/captures) page and reach out to me if you have any further questions.
