### ISSUE TITLE
Could not handle drive letter with lower case on Windows

### ISSUE THREAD

**Issue by formulahendry** [opticdev/optic#2810]
**Describe the bug**
Optic CLI could not handle drive letter with lower case on Windows.

**To Reproduce**
1. Create any openapi file Windows
2. Run CLI like `optic diff "d:\ApiCenter\test\test-api-spec\petstore.yaml"  petstore2.yaml  --check`, make the drive letter of file path with lower case

**Actual behavior**
Show weird error message:
![image](https://github.com/opticdev/optic/assets/1050213/53945bc8-14db-4df9-b255-d2218ea1363c)

**Expected behavior**
Need to handle drive letters in a case-insensitive way on Windows.
The Optic CLI need to work whether drive letter is lower case or upper case. 

**Details (please complete the following information):**
 - OS and version: Windows 11
 - Optic version: v0.54.12
 - NodeJS version: v20.9.0

**Comment by niclim** [comment]
Hi, I believe this should be fixed in `0.54.13` - thanks for reporting! Let me know if this is still an issue.
