### ISSUE TITLE
Highlight deprecated fields in history command output

### ISSUE THREAD

**Issue by amit-ng** [opticdev/optic#2846]
**Describe the enhancement**
Highlight deprecated fields when using history command, this will be really informative when generating change logs for end users.
Having this as always available in history command or adding a separate command will be great to have.

**Additional information**
We are planning to use Optic for our API change log documentation. We found that fields marked as deprecated are not captured in history command output. We feel this could a neat add-on to history command itself.

**Comment by amit-ng** [comment]
Seems like this support is available in some form. So will close this request.

**Comment by acunniffe** [comment]
Yeah it will show removed fields and added the attribute `deprecated` but it doesn't get any special formatting. If there's another way you'd like it to show up, feel free to copy some Optic history output, modify it, then share it here
