### ISSUE TITLE
api `intercept` command not found in v8

### ISSUE THREAD

**Issue by SatadruBhattacharjee** [opticdev/optic#364]
can't find the command api `intercept` , any other alternative for this. Like to record the requests from postman.

Thanks in advance

**Comment by LouManglass** [comment]
Hi @SatadruBhattacharjee ,

The `api intercept` command has been deprecated. Would you please let me know more about your project? For example, if it's an open source project, please point me to the repository. I can help you get started with the latest version following our [documentation](https://docs.useoptic.com). You can also use our [onboarding walkthrough](https://app.useoptic.com/) for a guided experience.

I'm sorry for the confusion, the intercept command shouldn't be documented anymore. Would you please let me know where you found it so I can update our documents?

**Comment by SatadruBhattacharjee** [comment]
Hi @LouManglass , thanks a lot for your response. I was trying to follow this tutorial https://www.youtube.com/watch?v=x6e6QJZ22l0 and noticed the command.

Unfortunately , it's not an Open Source project. I am planning to document some api endpoints (not all are developed by us)

**Comment by LouManglass** [comment]
@SatadruBhattacharjee Ah, great point, thanks! We want to do some tutorial updates, and I can see how that is currently confusing. We're sorry about that!

The best things to do would be to check out our resources, or book some time to chat. Any one of these links should get you going, based on your preferences:

- [Interactive setup walkthrough](https://app.useoptic.com/)
- [Getting Started documentation](https://www.useoptic.com/docs/getting-started/)
- [Chat with me](https://calendly.com/s/jrUptAcm)
