### ISSUE TITLE
[Question] how specify custom header request HTTP

### ISSUE THREAD

**Issue by c0ncentus** [opticdev/optic#38]
hi, 

i try some your exemple in the doc. 
If i got authetification or special header, how can i make it ? 

thanks and great job 👍

**Comment by acunniffe** [comment]
Hey @c0ncentus! 

Currently, custom headers aren't supported. We know it's a limitation and we're working on adding custom headers soon -- probably by the end of the year. 

As a workaround, you could write some custom markdown for the next few weeks:
<img width="715" alt="Screen Shot 2019-12-05 at 10 27 33 AM" src="https://user-images.githubusercontent.com/5900338/70249139-f7765400-1749-11ea-9800-7e4a65755bb2.png">

We think the feature will eventually work by adding a whitelist of headers to their `api.yml` and only have Optic learn those. What are all the headers you use today?

**Comment by c0ncentus** [comment]
Are you support this list when make request ? : 
1.  Authorization <---> jwt token [today i think i cannot use Optic due to this lack]
2.  Origin(for Cors concerned) 
3.  Cookie <---> For ETAG (is wow important) 

i can't find on the doc 🤔 


I keep watching this repo for evolution 🥇

**Comment by acunniffe** [comment]
These headers are not supported today, but we will add them soon.

Thank you for sharing your requirements. I'll let you know when the header parsing works so you can try it. 

I think you can use Optic for the rest of the API spec and add the docs for Authorization and Cookie manually for the time being. I know that's not ideal.

**Comment by LouManglass** [comment]
New request in #439, updated advice there for the latest UI
