### ISSUE TITLE
Is it possible to generate a static html doc website ?

### ISSUE THREAD

**Issue by abdelba** [opticdev/optic#39]
I'd like to serve the doc along with my API under the endpoint `/doc` but now for serving I need to run the `api spec` which is a node server that I have to host somehow.

Is it possible to generate html instead ?

Regards

**Comment by acunniffe** [comment]
Hey @abdelba -- that's a great idea. We've been working with some DevRel teams and this has been a common feature request. There's a fair amount of work to set up a new entry point / static HTML generation so it may take us a few weeks to fit it in. 

In the meantime, let me turn your attention to our generate command: 
`api generate:oas` -- exports an OpenAPI file (if you want yaml add the `--yaml` flag)

You can upload that to ReadMe, Slate, Swagger UI, etc. I know it's inconvenient to rely on a separate tool, I'm happy to spend a few minutes setting one of these up for you to save time. 

What do you think of the docs you see when you run `api spec`? Anything we could do to improve them?

**Comment by abdelba** [comment]
Hello @acunniffe, thanks for your reply.

In fact I knew about the generate option, but it gives me an error. I should open an issue for this maybe ?

```bash
$ api generate oas
Generating OAS file... !
 ›   Error: OAS Export Error{"error":"[Ljava.lang.StackTraceElement;@71623278"}
```

Here is the version I use
```bash
api --version
@useoptic/cli/6.4.4 darwin-x64 node-v12.13.1
```

About your question
> What do you think of the docs you see when you run api spec? Anything we could do to improve them?

I think it's great and for my use case where we have a few endpoints that we want to expose to an external partner it's doing a pretty good job. With Optic we are able to quickly setup a very good documentation because everything is already in Insomnia.

What can be easily improved I think is to specify the optional/required parameters directly on the UI while we review/complete doc, through some kind of check/uncheck or else.

Apart from that the main issue is the one I describe in the first message of his thread 😄 

Thanks

**Comment by acunniffe** [comment]
Hey @abdelba -

We did a big overhaul of the generate command this weekend -- it should be stable now. Update to the latest `6.5.1` and run `api generate:oas` -- note the command is slightly different. 

Awesome to hear! I'm glad the documentation flow is working well for you. The required / optional thing makes sense. I could see how it would be tedious to generate traffic with every permutation of polymorphism. I'll put a few cycles into thinking about how to make that easier. 

One of our goals for this week is to create an easy way to share specs. We're adding a share button to the local spec page that deploys it to a unique URL ie `apis.useoptic.com/3WHSkbM9zAU`. That's not quite what you're asking for but it might be a good interim strategy. 

Let me know if there's anything else I can do to help and thanks for using the project 😄!

**Comment by abdelba** [comment]
Very nice @acunniffe, the oas generation works perfectly now.
I'll give the share button when it's out 👍

**Comment by abdelba** [comment]
I was able to generate a beautiful doc using [shins](https://github.com/Mermade/shins)

I put it here as a workaround for reference.

```shell
yarn global add @useoptic/cli widdershins shins
api generate:oas
widdershins .api/generated/openapi.json -o /tmp/api.md
shins --inline -o doc/index.html /tmp/api.md
```

And voilà ! You have a beautiful html doc 😸

**Comment by acunniffe** [comment]
Amazing! That is really cool. I bet you could make a little script like `publish-docs.sh` to make it even easier to run all these commands. 

The OAS parser is missing examples and a few description fields. Feel free to open an issue if you want anything about the exporter changed. 

Really glad Optic was able to help you.

**Comment by acunniffe** [comment]
@abdelba -- I made a helper for you! Update to the latest CLI and add `publish.oas` to your `api.yml` file. 

Now you can run `api publish:oas`
1. This command runs `api generate:oas`
2. And then pipes the path into your command using the variable `{{{OAS_PATH}}}`

Now it's simple enough to run in CI 👍 

```yaml
name: Your API
commands:
  start: ...your start command...
  publish:
    oas: |
      widdershins {{{OAS_PATH}}} -o /tmp/api.md
      shins --inline -o doc/index.html /tmp/api.md
```

**Comment by abdelba** [comment]
Hey @acunniffe thanks for the helper 👍 

> Feel free to open an issue if you want anything about the exporter changed.

Doing that now.

**Comment by acunniffe** [comment]
Hey @abdelba -- we have share mode ready to demo! We're also thinking about different ways to generate static HTML. Would you mind video chatting for 30 mins something this month to talk more about your requirements for the feature? [Schedule a call](https://calendly.com/optic-onboarding/chat-with-aidan-clone?month=2019-12)

**Comment by LouManglass** [comment]
Update: Generating OAS is now done from the command line:

In case you need to be able to export to OAS, the generate OAS feature is available from the command line: `api generate:oas` will create an OAS file in JSON format (optionally the command takes the --yaml flag for YAML format) which you can then use in your tooling of choice.

**Comment by LouManglass** [comment]
@abdelba 

...and one more update! We just launched the Optic Scrips feature, which lives alongside Optic Tasks as a full-fledged, post-processing tool to address this issue. Optic Scripts are run from the command line with `optic scripts`, are defined in `optic.yml`, and automatically generate the latest OAS file which can then be manipulated by a script.

For example, we published a blog post that includes using [widdershins and shins](https://www.useoptic.com/blog/optic-scripts) to generate static documentation with the new Optic Scripts. Documentation is available at [Configuring Scripts](https://www.useoptic.com/docs/faqs-and-troubleshooting/scripts). Let me know if this helps keeps things running smoothly, and if we can make it work better for you.

**Comment by dheeraj100** [comment]
hello anyboby tell me can useOptics will generate html document?

**Comment by LouManglass** [comment]
Hi @dheeraj100 ,

Optic observes your API traffic and helps generate an API specification. You can then export this specification in OpenAPI format for other tools. For example, we published a blog post that includes using [widdershins and shins](https://www.useoptic.com/blog/optic-scripts) to generate static documentation with the new Optic Scripts. Documentation is available at [Configuring Scripts](https://www.useoptic.com/docs/faqs-and-troubleshooting/scripts). If you would like to generate an API specification with Optic, you can follow this blog post to generate HTML documentation as well.
