### ISSUE TITLE
GitBot for Azure DevOps

### ISSUE THREAD

**Issue by atnegrete** [opticdev/optic#396]
Integration with Azure Devops?

**Comment by LouManglass** [comment]
@atnegrete Thanks for checking in! I've spent some time in Azure DevOps and I think we could fit something in to help you out. What kind of integration with Azure DevOps would you like to see? Feel free to [schedule 15 minutes](https://calendly.com/s/vjwU3fAj) with me if you'd prefer to chat about it on a call.

**Comment by LouManglass** [comment]
We are working on a new and improved GitBot that will allow us to support other vendors, including Azure DevOps. For now, we can support some basic CI features in Azure DevOps such as failing a CI build when a difference in behavior from the spec. The `exit-on-diff` flag will fail the build by throwing a nonzero exit code (1 in all cases currently). This signals a failure which will allow for tasks to be run conditionally (for Azure DevOps, `condition: failed()` works to catch any failure).

The gist below will run tests against your application through Optic with a [dependent task](https://www.useoptic.com/docs/get-started/testing) configuration, and fail on differences in behavior.

[azure-pipeline.yml](https://gist.github.com/LouManglass/1b9a51cbbc9435443b0adb0579ddc7bf) gist

This should give you a good base to start from as we work on getting other features delivered.
