### ISSUE TITLE
"No results found" on demo code base

### ISSUE THREAD

**Issue by mmhaze2** [opticdev/optic#4]
Installed Optic and tried running it on the demo code. It shows as connected to vscode but shows "No results found" no matter what file I open. My job security worries have been alleviated.

**Comment by acunniffe** [comment]
Hey thanks for trying it out. We've never been after your job, just the boring work we'd all rather have automated. 

We need some better feedback when there's a null state like that -- feedback noted. I'm not entirely sure what would cause it to fail on that demo project but I'll look into the logs and see if I can find anything. Thanks again for trying us out.
