### ISSUE TITLE
[Doc] get started Optic

### ISSUE THREAD

**Issue by c0ncentus** [opticdev/optic#40]
On the doc, for lisibility can you make on 'get started'  some many gif for install optic on a server ?
(whatever project it is, just a pragmatical case ex for todolist)

when i asking 'Do you know what is optic ? see it' i would like of my partner will see quickly how Optic is great 🥇.

exemple see the readme how is beautifull [here is enquirer package](https://www.npmjs.com/package/enquirer)

thanks for the job what you done 👍

**Comment by acunniffe** [comment]
I think you're right -- I'll draft something up today & share it here for feedback from you and other community members.

**Comment by acunniffe** [comment]
@c0ncentus what do you think of this [readme](https://github.com/opticdev/optic/blob/develop/Readme.md)?

**Comment by c0ncentus** [comment]
It's sound great. 😄 

Maybe i don't fully understand. I used to 
1) write in programm a path
2) i test with postman

So for me doc is number 😢 .
I believe with optic is one thing to do : 
1) write a path and connect it on optic and launche optic doc for write the doc, maintain it, test it.

maybe I should try it i follow the use case for helping you.



For me "Test" is sending request and expected something but i see no infos about sending http request : / . I mess something (i see the doc) about Optic maybe
