### ISSUE TITLE
Improvements to openapi exporter

### ISSUE THREAD

**Issue by abdelba** [opticdev/optic#41]
Hello, 

It seems that in the openapi exported file is missing some fields.
When I try to generate an html using shins (see https://github.com/opticdev/optic/issues/39) I have some discrepancies like

- The name of the endpoint is some random id like `request_xxxxxxx` while I'd like to be the same title as in the `api spec` view

- generally speaking we miss a lot of user added info like descriptions and IMO it can be simple to add these and enrich the openapi file and thus all generated doc from it.

**Comment by acunniffe** [comment]
Hey! I'm looking into this now. The intended behavior is for the generator is to map Optic's 'Purpose' field to OpenAPI `summary` and Optic's 'Description' field to OpenAPI `description`. `request_xxxxxxx` looks like an Optic Request ID which should be mapped to OpenAPI's `operationId`.

<img width="1539" alt="Screen Shot 2019-12-11 at 1 56 57 PM" src="https://user-images.githubusercontent.com/5900338/70651110-3f035100-1c1e-11ea-8800-5efacbdb43b9.png">

I think there was a bug where operationId and summary were swapped. Update to the latest and try again, please. 

> generally speaking we miss a lot of user added info like descriptions and IMO it can be simple to add these and enrich the openapi file and thus all generated doc from it.

Do you mean fields? I'm planning on adding a way to add descriptions to individual fields this weekend :) stay tuned!
