### ISSUE TITLE
[Question] Can Optic support pipeline test api features ?

### ISSUE THREAD

**Issue by c0ncentus** [opticdev/optic#42]
Hello, 

What i expected is :
When you make devops, you just test all things with command pipeline on travis like : 
npm i && npm i -g mocha && npm test && cd ./things && ts-node file.ts

optic provide a command line for test all the doc ? 

![optic](https://user-images.githubusercontent.com/25374826/70696382-dec6ea80-1cc3-11ea-86b0-2694f6f5bea6.jpg)

**Comment by acunniffe** [comment]
@c0ncentus - we can definitely add something like that. How are you testing the API today? Are there manual tests for the API you have already written? 

What kind of errors would you expect Optic to produce?

**Comment by c0ncentus** [comment]
# Suggestion
For this moment i dev a api generator so ... I have time :) .
now, i make manual testing with postman 😄. Otherwise i've already make request test with axios and mocha/chai.

when test fail, i would like know:
```Typescript 
`${customTitle} not pass. Excepting ${excepting}`
```
or
```Typescript 

`Fail on ${url} with method ${method}. Excepting ${excepting}`
```
*Expecting maybe is too difficult to have and optional because you can check with doc 😄

what you think about  ?

**Comment by LouManglass** [comment]
@c0ncentus We've been making a few changes to the project, specifically around CI workflows like this. Thanks for your feedback, it's been helpful! Keep an eye out on the latest versions, and on our [documentation](https://docs.useoptic.com/) for upcoming features that will help you get this kind of information.

**Comment by LouManglass** [comment]
@c0ncentus We're currently working on the best way to integrate with CI pipelines and have published a basic way to get Optic providing checks for [GitHub Actions](https://www.useoptic.com/docs/change-management/optic-ci). We'd like to improve support for this and assure it works generally across CI tooling. Please let us know how this works for you, and what tools you use, and we're happy to incorporate your feedback.

**Comment by LouManglass** [comment]
@c0ncentus I've been testing the `--exit-on-diff` flag for a bit, and I think this captures the basic ask. On its own it doesn't give you more detail into what was expected. The example gist below runs a test called `run-diff-tests` (this would be any [dependent task](https://www.useoptic.com/docs/get-started/testing) you've set up to run tests). If a diff in behavior is detected, it throws an error (failing the check) and comments that a diff was detected. As it doesn't go into the detail on expectations, it adds a comment to the PR asking the developer to run the tests locally and review the results.

[main.yml](https://gist.github.com/LouManglass/3470d8dec90faf35363caa68ec36bcf6) gist.

We're working on adding richer context directly in the PR. For now, I trust this is a good workaround to supporting testing in the CI pipeline and provides a basic structure to build on.
