### ISSUE TITLE
Failed to handle request: aborted

### ISSUE THREAD

**Issue by ViRb3** [opticdev/optic#426]
I am running Optic in proxy mode, and some of the endpoints fail with:
```
Failed to handle request: aborted
```
As far as I can tell, and this may be a coincidence, but these endpoints return a pretty large JSON response (7000 lines), and Optic seems to bail at that sight. is there any way to increase the maximum line limit?

**Comment by LouManglass** [comment]
Hi @ViRb3 ,

I'm not aware of an explicit line limit, though I suppose there could be several things going on here. The best thing to do would be to collect some troubleshooting data. If you can share a [debug session](https://www.useoptic.com/docs/faqs-and-troubleshooting/debugging) this would help us reproduce the issue on our end and dig into it. The debug session strips out all data values, leaving only endpoints, keys, and a [traffic shape hash](https://github.com/opticdev/shape-hash).

Failing that, we can try to dig into a few other options. For example, we can help you start a detailed debugging session of the Optic proxy. Let us know your development environment, and we can work with you to get some logs. It's not as helpful as a debug session above, but it's certainly a step towards resolving this issue.

**Comment by ViRb3** [comment]
Hello,

I am more than happy to share a debug session, but the error happens before the endpoint is able to be added to Optic's database. In the debug session, there is no sign of the endpoint that causes the issue. Anyway, the API is public, so feel free to try it for yourself. The endpoint is as follows:
```
https://addons-ecs.forgesvc.net/api/v2/minecraft/modloader
```

**Comment by LouManglass** [comment]
Ah, excellent! Let me try to reproduce it on the public API first then. Thanks for pointing that out, there's no need for a debug session at this point. I'll follow up in the next few days with some thoughts.

**Comment by LouManglass** [comment]
Hi @ViRb3 ,

I sent a `GET` request to that path both directly and through the latest version of Optic using Postman. In both cases, I saw a payload return of around 400 KB (they varied by about .02 KB per request as reported by Postman). The Optic request contained 23235 lines of JSON, definitely over 7000.

In both cases my responses returned in under a second, and Optic didn't seem to have any issues fetching the data or documenting it in the Optic dashboard. Is there any chance that there are network issues on your end which could be causing the request to abort, or any other network configurations that would help debug this further?

Another question I have is, what version of Optic are you running? You can find that with `api --version`. If it's earlier than 8.5.0 I'd suggest an update. You can update to the latest with [several package managers](https://www.useoptic.com/docs/getting-started/install). For example, with npm, you can run:

`npm install --global @useoptic/cli`

**Comment by ViRb3** [comment]
Hello,

Thank you for the dedicated time once again. Indeed, I ran Optic through the above endpoint separately from my project, and it worked like charm. I dug into the problem and it turns out the culprit was my custom proxy, which I use to modify Optic's requests before they reach the API server. I was closing the response before reading it, and in the case of longer response bodies, I was effectively closing the body before all of it had passed through Optic, so it obviously couldn't parse it. I have now fixed that and everything works great again. Sorry for the false alarm, and great job on Optic!

**Comment by LouManglass** [comment]
Thanks for the kind words! You're very welcome for the time, and we appreciate the follow-up. We definitely don't want you to run into issues no matter the cause, though we do appreciate being able to rule out anything odd with Optic in a deployed environment in this case.

Please keep us informed on your projects, and let us know if you run into any other issues.

**Comment by ViRb3** [comment]
For the record, here is the library that I was building when I encountered this issue: https://github.com/ViRb3/optic-go

And this is the crucial piece of code, if anyone else stumbles upon this issue:
```go
	// drain the body to make sure all of it passes through Optic, otherwise we could cut it off
	if _, err := io.Copy(ioutil.Discard, resp.Body); err != nil {
		return err
	}
```
