### ISSUE TITLE
Cannot edit API spec path when documenting a new request

### ISSUE THREAD

**Issue by gaurav-nelson** [opticdev/optic#43]
Thanks for this tool. It does looks promising. 

When adding a path in Document a New Request. If I entered a wrong path in `2. Add path to your API spec` field and added it, there is no way to modify the path unless I close and restart again.

Maybe a back button would help here or some other way to edit that.

![image](https://user-images.githubusercontent.com/23069445/70757626-01243b00-1d8c-11ea-84e8-59e2ac0b5887.png)

**Comment by acunniffe** [comment]
@gaurav-nelson thanks for the feedback. We have a redesign of this page coming this month. It makes writing the path matcher easier and allows you to back track. 

In the current UI you can click the number 1 bullet to restart — sorry it is not more obvious.

**Comment by acunniffe** [comment]
Hey @gaurav-nelson  -- check out the latest version of Optic. @devdoshi made the path matcher much easier to use!
