### ISSUE TITLE
Support gitlab CI

### ISSUE THREAD

**Issue by theArtechnology** [opticdev/optic#442]
Add to GitLab CI

**Comment by LouManglass** [comment]
@theArtechnology We can certainly look at that, thanks for reaching out! We're currently working on our CI integration process to make it more flexible, so adding other providers like GitLab CI will be more feasible. Are there any features of the current GitBot in GitHub that are particularly interesting, or anything that you'd like to see that we haven't yet implemented there? That can help us prioritize work going forward to build the most useful GitLab CI integration.

**Comment by LouManglass** [comment]
We're working towards improving the CI integration process, and have some news: the `--exit-on-diff` flag will provide the basic ability to pass/fail checks in Gitlab CI. While more features are in the works, the ability to pass/fail checks provides a good bit of CI support today when used with conditional jobs (such as `when: on_failure`).

[.gitlab-ci.yml](https://gist.github.com/LouManglass/1fe3c672dd55298f1b250ac362f3bf98) gist
