### ISSUE TITLE
Origin headers can break CORS when Optic is used transparently

### ISSUE THREAD

**Issue by LouManglass** [opticdev/optic#492]
When using CORS in development environments, CORS checks such as [Verifying `Origin` with standard headers](https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#verifying-origin-with-standard-headers) can fail with Optic when used transparently (_i.e._ when accessing server resources via `localhost`). The `Origin` header will not match the target site if it is fetched by an FQDN, and the scheme/protocol may also fail even if the server is running on localhost. Proxies should make this clear through some mechanism such as `Forwarded`/`X-Forwarded` headers.

**Workaround** This is not an issue when the proxy is configured explicitly. For example, when running Chrome, start a session that explicitly sets the proxy to Optic's inboundUrl:

`chrome --proxy-server="http://localhost:<Optic inbound port>"`

Then navigate to your service using its FQDN as normal.

**Comment by acunniffe** [comment]
@LouManglass  -- I can see (at least) two acceptable solutions here:

1. Rewrite the header, either by default, or when a flag is specified in optic.yml or the command -- not sure what all the externalities of rewriting in every case are 
2. Bring back `api intercept` mode flags that were removed in the spring, so `api start --chrome` would open a fresh browser with the right proxy config and point users towards that when using the browser to consume API's under observation

**Comment by LouManglass** [comment]
My inclination is less rewriting, more matching the customer's expected workflow. This also avoids issues such as cookie domains from biting us later. 

A nice to have on 2 would be to include a `--firefox` and/or `--safari` flag as well, being the next highest browsers in use on "desktop". These aren't critical though, Chrome does has the lion's share and Firefox has options like Foxyproxy that are pretty straightforward to set up.

**Comment by LouManglass** [comment]
This should be resolved with the `OPTIC_ENABLE_TRANSPARENT_PROXY` environment variable set to `yes`, which should forward traffic as intended. That is:

- `OPTIC_ENABLE_TRANSPARENT_PROXY=yes api run start` to run the Start command with the transparent proxy mode set
- `chrome --proxy-server="http://localhost:<Optic inbound port>" --allow-insecure-localhost` to have Chrome proxy through Optic locally, and ignore the certificate error otherwise thrown by Optic's self-signed certificate when using SSL/TLS.
