### ISSUE TITLE
Filter traffic popup should automatically close if clicking outside the popup area

### ISSUE THREAD

**Issue by syte** [opticdev/optic#507]
Currently whenever you open up the filter traffic popup menu there isn't a good way to close it other than by selecting a new filter option or navigating away from the page. I would expect it to automatically close if I click anywhere outside the popup.
![Screen Shot 2021-01-14 at 9 40 39 AM](https://user-images.githubusercontent.com/2949177/104605718-d8383e80-564c-11eb-98ad-4864e38c5b7e.png)

**Comment by acunniffe** [comment]
@syte -- good find! thanks. that's officially the last bug fix to make it into Optic 9, the final PRs have been landing all day

one line fix
https://github.com/opticdev/optic/commit/6a2b593d54ce892d7030aef7a4cd507885d2d744

we're rethinking how captures would. Is the start/end of a process a good boundary, or would it make more sense to group traffic by something else?

**Comment by syte** [comment]
Hey @acunniffe, I feel like the filter right now isn't as useful. I won't have a clear sense of what api endpoints were added 13 mins ago vs 26 mins ago. Is it possible to remove the filter altogether and just show all the endpoints? Thanks for the fix by the way!
