### ISSUE TITLE
Diff and undocumented URLs endpoints timeout

### ISSUE THREAD

**Issue by bethesque** [opticdev/optic#520]
## Software Versions

@useoptic/cli/8.6.2 darwin-x64 node-v10.16.0
Mac Mojave 10.14.6
Chrome 87

## Expected behaviour

Can view diffs and undocumented URLs in Optic browser console.

## Actual behaviour

Diff and undocumented URLs endpoints timeout when rendering the browser console. The spinner next to "0 PROCESSED | 0 SKIPPED" keeps spinning. The captures and samples endpoints return with successful responses.

## Steps to reproduce

```
git clone git@github.com:pact-foundation/pact_broker.git
cd pact_broker
bundle install
npm install @useoptic/cli@^8 -g
api run start

# in another console

./script/exercise-api-for-optic.sh
```

Click on the use optic link in the output.

## Logs

```
pact_broker $ api run start
[optic] Review the API Diff at http://localhost:34444/apis/1/diffs
[optic] Optic is observing requests made to http://localhost:4000
...
[2021-01-19 16:46:08] INFO  WEBrick 1.7.0
[2021-01-19 16:46:08] INFO  ruby 2.7.2 (2020-10-01) [x86_64-darwin18]
[2021-01-19 16:46:08] INFO  WEBrick::HTTPServer#start: pid=21960 port=3332
::1 - - [19/Jan/2021:16:47:08 +1100] "DELETE /integrations/provider/MyProvider/consumer/MyConsumer HTTP/1.1" 204 - 0.6470
::1 - - [19/Jan/2021:16:47:08 +1100] "POST /pacticipants HTTP/1.1" 201 1041 0.0102
::1 - - [19/Jan/2021:16:47:08 +1100] "POST /pacticipants HTTP/1.1" 201 1041 0.0098
::1 - - [19/Jan/2021:16:47:08 +1100] "PUT /pacticipants/MyConsumer/versions/1/tags/main HTTP/1.1" 201 399 0.0160

... more web logs here showing successful HTTP requests and responses

^C[2021-01-19 16:47:13] INFO  going to shutdown ...
[2021-01-19 16:47:13] INFO  WEBrick::HTTPServer#start done.
[optic] Observed Unexpected API Behavior. Click here to review: http://localhost:34444/apis/1/diffs/91b2aa92-58b5-440c-bb89-8762d553734d
```

[debug-capture-c9ef8ec6-15d2-44b4-9c9c-e2950ba0b305-1611034792.json.txt](https://github.com/opticdev/optic/files/5833883/debug-capture-c9ef8ec6-15d2-44b4-9c9c-e2950ba0b305-1611034792.json.txt)

<img width="1085" alt="Screen Shot 2021-01-19 at 4 41 35 pm" src="https://user-images.githubusercontent.com/446228/104993107-745fac80-5a76-11eb-9adc-61f541f12668.png">

## Notes

This issue was not able to be reproduced on my workmate's Mac (ie. everything worked as expected). So it seems it must be something specific to my set up, but I'm at a loss to what it could be. I have tried uninstalling and re-installing the npm package. I have tried viewing the optic console in Safari and Chrome. I have made sure Little Snitch has been turned off.

I have just tried installing from scratch in node 12, and I get even less of the screen displayed (it's just white with the loading bar scrolling across the top), but a bunch of requests going to nimbleswan.io and rs.fullstory.com.

<img width="860" alt="Screen Shot 2021-01-19 at 7 57 15 pm" src="https://user-images.githubusercontent.com/446228/105011956-b64a1c00-5a91-11eb-8809-72782be443f2.png">

<img width="668" alt="Screen Shot 2021-01-19 at 8 05 26 pm" src="https://user-images.githubusercontent.com/446228/105012036-ccf07300-5a91-11eb-9233-63af0753bb55.png">

I would appreciate any pointers as to what could be the issue.

**Comment by bethesque** [comment]
I uninstalled the global npm package and installed useoptic via brew. The diff endpoint still hangs.

<img width="1102" alt="Screen Shot 2021-01-19 at 8 53 36 pm" src="https://user-images.githubusercontent.com/446228/105018049-9ff38e80-5a98-11eb-93a3-c1debf26de0d.png">

**Comment by LouManglass** [comment]
@bethesque Hi Beth! I'm sorry for the problem, that seems really frustrating since it works on your workmate's Mac. Thanks for the detailed report. I suspect that Optic 8 is having a bit of a time crunching through some of the data, and my first suggestion would be trying out our latest version which we just released. Both Brew and NPM should have the latest available Optic version, 9.0.4 at this moment. I saw you started with NPM, I'd suggest uninstalling via Brew and installing via NPM:

`brew uninstall opticdev/optic/Api`
`npm install --global @useoptic/cli@9`

The latest version is much faster, and we'd recommend it for both you and your workmate. If this doesn't resolve your issue, let me know if any symptoms change and we can troubleshoot further.  I'm also happy to [set up a call](https://calendly.com/s/KKLX0aVc) if you want to take a deep dive into getting this resolved.

**Comment by devdoshi** [comment]
@bethesque also you'll need node >= 12

**Comment by bethesque** [comment]
Thanks @LouManglass. I've updated to version 9 on npm v12, and the same issue is occurring.

<img width="809" alt="Screen Shot 2021-01-22 at 8 57 42 am" src="https://user-images.githubusercontent.com/446228/105417736-21f9d800-5c90-11eb-869d-5ffc2d75e895.png">

My gut feel is that it might be some issue to do with the older version of Mac OS I'm running, as it worked fine on my colleague's Mac. I understand that there might not be anything you can do about this, but maybe someone else might have the same issue, so at least it's on record.

**Comment by LouManglass** [comment]
@bethesque Oh no! Thanks for getting that on record, and for sharing all the troubleshooting information and comparative results with your colleague. I'll see if I can spin up a comparable environment and attempt a reproduction as well. I'm not sure what we can do for your version of Mac OS, but if I find any quick wins I'll be sure to let you know.

Is there anything I can do to help? If you want to give some alternative method to running Optic on your MacOS host a try, let me know.

**Comment by bethesque** [comment]
It's not blocking me on anything, as I was just spiking some things out to see how the tool worked. Thanks for your help. I'll close this for now, and re-open if anything changes.
