### ISSUE TITLE
delete an api endpoint ?

### ISSUE THREAD

**Issue by lvenier** [opticdev/optic#55]
Hi,

Is that possible to remove an api endpoint  ?

Rgds

**Comment by acunniffe** [comment]
Hey @lvenier  -- we need to build some UI for that. 

Are you trying to delete an entire path ie `/users/:userId/` with all its methods
or a single request `POST /users/:userId`?

**Comment by lvenier** [comment]
a single endpoint

**Comment by acunniffe** [comment]
Ok -- UI will be out soon. Deleting paths is harder because there can be side effects. 

Cheat code! Add this event to the bottom of your spec store:
```
{"RequestRemoved":{"requestId":"request_m5B1HIkLF2"}}
```

`requestId` should be easy to find by looking in your address bar

**Comment by lvenier** [comment]
got it.
we'll give it a try :)

**Comment by lvenier** [comment]
I confirm it does work by adding the RequestRemoved...
Thanks

**Comment by LouManglass** [comment]
The earlier workaround is no longer suggested. Instead, we recommend upgrading to the latest version which includes a debugging tool to remove endpoints. This is available starting in the Optic CLI starting with 9.0.13:

- Identify the `pathId` of the endpoint to remove by clicking on the full documentation link  for the endpoint endpoint in the Optic dashboard. 
  - If the dashboard isn't open, run `api spec` in the project directory. This will open the documentation in the Optic dashboard.
  - The `pathId` will show up in the path of the URL as `path_` with ten alphanumeric characters following. For example, the `pathId` might be `path_nLY8r21Sg7`. Note this ID and the method (such as `GET`).
- Delete the endpoint with `api debug:endpoint-delete <method> <pathId>`. For the example above, the command would be `api debug:endpoint-delete GET path_nLY8r21Sg7`
- Refresh the documentation page - the endpoint has been deleted.

**Comment by LouManglass** [comment]
With the release of Optic 10.1, you can now delete endpoints by editing your documentation, clicking the delete button, and saving the changes to your spec. This can be done from either the general documentation page for any endpoint, or from the detailed endpoint documentation page for a specific endpoint. If you have bulk changes to make that line up with a recent learning session, there's also the ability to revert a documentation commit on the history tab.

With this release, the debug endpoint on the CLI has been removed and is no longer recommended. If you need to delete an endpoint, please upgrade to Optic CLI 10.1 or later:

```npm install --global @useoptic/cli```
