### ISSUE TITLE
API Init: Is there a way to integrate with integration test?

### ISSUE THREAD

**Issue by rhzs** [opticdev/optic#552]
Hi,

Currently we are trying to integrate optic with our CI/CD pipeline in Integration Test stage. 

During the integration stage, we do API testing to against the server using Laravel Unit Test library. 

I have seen the [Laravel docs](https://useoptic.com/docs/laravel) but it only covers the integration when the server is up and running.

Is it possible to integrate Optic with existing our integration test stage? 

Any help would be appreciated. Thank you. :)

**Comment by LouManglass** [comment]
Hi @rhzs,

It is currently possible to integrate Optic with any tests that send network traffic, such as my understanding of Laravel Unit Test Library, and we're working on making Optic even more capable in CI. The general idea is you would run your tests with a [dependent task](https://www.useoptic.com/docs/get-started/testing) via Optic, which allows Optic to not only run the Laravel server but also run the tests. This allows Optic to observe the test traffic. You may be particularly interested in the `--collect-coverage` flag as well (there's a demo at the bottom of the documentation page above

The output can be reported through the tools (such as in a Pull Request comment) or used to make decisions in the CI/CD pipeline. Every environment is different, and I can't make an effective blanket recommendation, but I'd be happy to chat with y'all a bit. We can discuss further here, or feel free to [grab some time](https://calendly.com/s/dJxllYau) on my calendar and we can pair a bit to find the best fit for your workflow. Let me know what works!
