### ISSUE TITLE
api spec error message

### ISSUE THREAD

**Issue by lvenier** [opticdev/optic#56]
when I run :  
```# api spec```

I got the following output : 
```[Error: ENOENT: no such file or directory, open '/var/tmp/shaq/.api/sessions/interceptor-session.optic_session.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/var/tmp/shaq/.api/sessions/interceptor-session.optic_session.json'
}
```

to make it work I have to open a second console with # api intercept

did I miss a config somewhere ?

**Comment by lvenier** [comment]
it is working now. not sure of what I have done.
you can close and if it reoccurs I try to get more input to reproduce it

**Comment by acunniffe** [comment]
Thanks! Also Optic 7 is coming out very soon (within days) and it fixes a lot of things around sessions. Now things work live so you don't need to switch between `start` and `spec`
