### ISSUE TITLE
Environment variable $PORT not recognised in Flask API

### ISSUE THREAD

**Issue by jordaniza** [opticdev/optic#565]
Hi guys,

Really appreciate the idea of optic, and I hope this is a simple misunderstanding of the app on my part, but I've hit a wall in trying to start a simple flask application.

The issue:
I am not able to follow the quick start guide to launch an application because the $PORT setting is not being detected when running optic. If, instead, I try to remove the $PORT env var, and hardcode values, optic is not reliably able to track my diffs.

Env:
- Windows 10 
- Flask 1.1.2
- Python 3.8.2
- npm 6.13.4
- VS Code/PowerShell

- In `optic.yml` , as per the quickstart guide, I have added:

```
tasks:
  start:
    command: "flask run --port $PORT"
    inboundUrl: http://localhost:4000
```

When I run `api check start` the results are as follows:

```
Your command: flask run --port $PORT
  × Starts a long running process (your API)
    → Your command exited early
    On the host Optic assigns it $HOST (current: localhost)
    On the port Optic assigns it $PORT (current: 3405)


Given this inboundUrl: http://localhost:4000
  √ Optic proxy is able to start its proxy here localhost:4000

[optic] Some checks failed. Steps to fix can be found here: useoptic.com/docs/check-fail
```

I should mention here the url useoptic.com/docs/check-fail doesn't go anywhere.

Ok, no problem, let's just try `api start`...

That unfortunately fails because `Error: Invalid value for '--port' / '-p': $PORT is not a valid integer`

So looks like the env variable $PORT is not being passed from optic to my CLI

I can do a couple of things:

1. I can remove the $PORT variable from the YAML file, then `api start` runs fine
2. I can hardcode a port variable and a hostname and the `api start` command works, but unfortunately does not capture diffs
3. I have tried different combinations of ports and hostnames and same results:
    - port==hostname
    - port!=hostname
    - host == localhost
    - inbound url == localhost @ port

A run of `api status` gives the following:
```
[optic] Observed Unexpected API Behavior. Run "api status"
(venv) PS C:\...\api> api status
computing diffs for observations 2/2... done
✓  No diffs observed for existing endpoints
   Undocumented URLs observed
      (use "api status --review" to start documenting them
          GET   /
```

**Comment by acunniffe** [comment]
@jordaniza thanks for the long description and sorry for the issue getting started with Optic. 

If I had to guess -- it looks like the `$PORT` in your command is not being evaluated as something python can parse to an integer. Flask is probably grabbing everything after `--port` and trying to make it a number for the port it's binding to. 

Most of our guides were written in a bash env, and I suspect there's something about Powershell Optic needs to encode better. 

Can you try running `api run check` and `api start` from bash? I suspect it will work, but obviously that's not a long-term solution. 

@LouManglass knows more about how Optic works with various shells than anybody. He's helped teams use Optic in crazy environments over the last few months. He will chime in here Monday. 


Re: docs link -- good catch. I'll open a PR for this shortly.

**Comment by jordaniza** [comment]
Suspected as much, I'm running the main app inside a debian container, so I'll give it a go in there today.

**Comment by LouManglass** [comment]
@jordaniza @acunniffe Howdy! This is something I was digging in to Friday by chance, and it's related to how the underlying Node code spins up a shell. Even when you're in Powershell, it's starting a command shell under the hood when you start your project. We'll update the documentation to avoid this in the future, and I'm sorry you ran into this issue.

In the mean time, please use `%PORT%` to indicate the port (as opposed to $PORT) on Windows. You can test this yourself by setting the command to `echo %PORT%` and running `api start`. You should see the port print out. Note this won't pass a check, and is purely diagnostic.

If your project is cross-platform, there are ways to make this a bit more friendly. I'm happy to dig into this further with you if that will help.

**Comment by jordaniza** [comment]
Hi both, 

@LouManglass: `%PORT%` solves the problem, thank you.

As a side note, I'm a bit slow and failed to understand the role of the proxy vs. inbound url.

I can now see that the proxy runs on whatever port it needs to as determined by the `%PORT%` variable, whereas you've provided the utility to let me run my flask app on the regular port 5000, I hadn't appreciated that first time around, hence I was experimenting with having them run on the same port which of course wasn't doing anything.

Diffs are now being captured on the Optic review panel :) I've also been able to fire up `pytest` and run the test suite, which I was not able to before.

Thanks again for the quick support. Really looking forward to using this. +1 star from me 👍

**Comment by LouManglass** [comment]
@jordaniza Thanks for the kind words! If you have any recommendations on how we can clarify setup, I'm all ears. We definitely don't want it to be confusing or hard to understand. There's definitely a hurdle to get over when setting up, like with any new software, and we'd prefer it to be as close to a well-worn speed bump as possible.

Have a great time, and enjoy! We're here if you have further questions.

**Comment by jordaniza** [comment]
Hi Lou,

I've put some proposed changes to the docs in pull requests. Feel free to use them or discard - thought it would be easier than replying here.

Closing this issue for now, thanks for your help :)
