### ISSUE TITLE
"api init" broken with Homebrew install (SyntaxError: Unexpected token {)

### ISSUE THREAD

**Issue by solarmosaic-kflorence** [opticdev/optic#570]
Installed via `brew`:
```
➜  brew install opticdev/optic/api
==> Tapping opticdev/optic
Cloning into '/usr/local/Homebrew/Library/Taps/opticdev/homebrew-optic'...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 757572 (delta 0), reused 4 (delta 0), pack-reused 757565
Receiving objects: 100% (757572/757572), 303.35 MiB | 14.76 MiB/s, done.
Resolving deltas: 100% (502944/502944), done.
Tapped 1 formula (28 files, 323.6MB).
==> Installing api from opticdev/optic
==> Downloading https://homebrew.bintray.com/bottles/node-15.4.0.catalina.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/9fd658c97b8b6d2c075b72f3bd683202e83dcc6926bb7c2a784d1c1a595f0739?response-content-disposition=attachment%3Bfilename%3D%22node-15.4.0.catal
######################################################################## 100.0%
==> Downloading https://registry.npmjs.org/@useoptic/cli/-/cli-9.0.10.tgz
######################################################################## 100.0%
Warning: Your Xcode (11.3) is outdated.
Please update to Xcode 12.2 (or delete it).
Xcode can be updated from the App Store.

==> Installing dependencies for opticdev/optic/api: node
==> Installing opticdev/optic/api dependency: node
==> Pouring node-15.4.0.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/node/15.4.0: 3,273 files, 55.4MB
==> Installing opticdev/optic/api
==> npm install -ddd --global --build-from-source --cache=/Users/kflorence/Library/Caches/Homebrew/npm_cache --prefix=/usr/local/Cellar/api/9.0.10/libexec /private/tmp/api-20210208-51291-p5az8p/pac
🍺  /usr/local/Cellar/api/9.0.10: 56,601 files, 262.4MB, built in 5 minutes 1 second
==> `brew cleanup` has not been run in 30 days, running now...
```

Tried to `api init` and got a failure:

```
➜  api
API CLI from Optic. Document and test your APIs as you build them.

VERSION
  @useoptic/cli/9.0.10 darwin-x64 node-v9.6.1

USAGE
  $ api [COMMAND]

COMMANDS
  check     verify that Optic can run your tasks and monitor traffic
  generate  export an OpenAPI 3.0.1 spec
  help      display help for api
  init      add Optic to your API
  run       run tasks from your optic.yml
  scripts   run one of the scripts in optic.yml with the current specification
  spec      open your current API specification
  start     alias for "api run start"
  status    lists API diffs observed since your last git commit
➜  api init
    SyntaxError: Unexpected token {
```

Mac OS 10.15.7 (Catalina).

**Comment by LouManglass** [comment]
Hi @solarmosaic-kflorence 

Thanks for the detailed issue log! From the `api` command, it looks like you're currently running `node-v9.6.1`. Optic requires a minimum Node version of 12. Our Brew tap manages the prerequisite, though it appears your local environment may have another preferred way of managing Node versions. I'm sorry for the confusion.

The quickest path forward would be to use [Yarn or NPM to install  Optic](https://www.useoptic.com/docs/) instead of Brew for the time being. These are better aware of your Node version managers and should work as intended. You can also upgrade your version of node to a newer version using your node manager of choice, such as Node 14 (the latest LTS version).

We'll improve the Brew formula to help make this clearer going forward. Let me know if I can help out in any other way.

**Comment by solarmosaic-kflorence** [comment]
@LouManglass thanks, I was just going down the route of updating node and trying to use it via `npm`. I will also try using the `brew` version with a newer node and report back here.

**Comment by solarmosaic-kflorence** [comment]
@LouManglass updated to node `15.8.0` and it works fine now. Perhaps the install page should mention which version of node/npm are required. Otherwise this can be closed out.

**Comment by LouManglass** [comment]
@solarmosaic-kflorence I'm working on the documentation page later today, I'll include this minimum requirement there as well so it's visible. Thanks for confirming that worked, and didn't reveal any further issues. 

Enjoy, and let me know if we can help out in any other way!
