### ISSUE TITLE
CI Enforcement

### ISSUE THREAD

**Issue by solarmosaic-kflorence** [opticdev/optic#578]
Is there any way to ensure that optic is up to date with all code changes? The only way I can think of is to run optic in the CI system and see if it generates a different spec than what was committed, but that doesn't seem like a great solution. I see the suggestion of a git pre-commit hook, but I need ways to enforce usage from the CI servers perspective.

**Comment by LouManglass** [comment]
Hi @solarmosaic-kflorence,

I'm not quite sure I'm clear on your goal, based on the description - what are the downsides to running Optic in your CI? I can offer some background and dig into this with you further to find the best fit. Optic builds your spec by observing traffic, watching the behavior of the code (not the code changes itself). To ensure the spec is up to date, Optic should be running any time you're sending sample traffic in your local developer environment, and we do suggest running your tests in CI for Optic to observe and catch any behavior changes that weren't observed locally.

Optic has the capability to run your tests in CI with [dependent tasks](https://www.useoptic.com/docs/get-started/testing), and we're working on some features to help check the status of your local work (to make sure observed differences are fully documented in the spec and allow for git pre-commit hooks) and give you more power in CI (such as clearer ways to fail a build if your observed traffic disagrees with your specification). If the CI server needs to enforce usage, running tests in CI through Optic seems the best fit.

Every team is different, and I'd be happy to get you the current capabilities to best fit your workflow. Do any of these capabilities look like a fit, or are your requirements different? We can dig into a deeper discussion if you'd like, feel free to book time to [chat](https://calendly.com/s/IRVYSz5a)

**Comment by solarmosaic-kflorence** [comment]
@LouManglass I appreciate all your quick replies :)

I have no problem running optic as part of my CI tests, I'm just trying to figure out the best pattern so that if the developer added/changed some functionality but did not update optic as part of their commit, it will fail. It seems like maybe `api status --pre-commit` will do what I want, if I execute that after tests have run (if there is a diff, it will fail the build)? If that's the case, maybe a better name for that flag would be something like `--fail-on-diff` or `--check`.

This is kind of similar to how we enforce code style settings. Our developer is required to run a command locally to ensure their code is formatted correctly, and then in the CI build we run a check to see if all code is formatted correctly and if it's not, we fail the build.

**Comment by LouManglass** [comment]
You're very welcome! I appreciate the added context, I see where my misunderstanding was.

Yes, `api status --pre-commit` will help you out there. It exits 0 when no diffs or undocumented URLs are observed, and 1 if there are any changes to resolve. It's intended to use in a pre-commit hook, allowing you to abort the commit if the status isn't clean. I'll pass the naming feedback along, as we intend to make features like this available throughout the project lifecycle (such as passing or failing a build in CI). A more general name could help.

If you give that a try as a pre-commit hook, or want to try some other pattern, let me know. I'd be interested to hear the results and dig in further on any questions.

**Comment by LouManglass** [comment]
@solarmosaic-kflorence When running Optic as part of your tests, the latest build allows you to pass the `--exit-on-diff` flag which will throw a nonzero exit code (currently, always 1) when Optic detects a difference in behavior from the specification. You could use this in CI alongside [dependent tasks](https://www.useoptic.com/docs/get-started/testing) to run your tests with Optic to see if there's a violation.

[mail.yml](https://gist.github.com/LouManglass/3470d8dec90faf35363caa68ec36bcf6) is a gist showing an example GitHub Action that runs a hypothetical `run-diff-tests` task that will show some diffs. On failure, the action posts to the GitHub PR with next steps for the developer to review the test traffic locally and resolve the differences.

Does this look more in line with what you need? Can I help tune that up for you a bit?

**Comment by solarmosaic-kflorence** [comment]
@LouManglass awesome! that looks like it will solve this issue for me. Unfortunately I've put our Optic integration on hold until query parameters are implemented, but I hope to work on our Optic integration in the background as time allows as I think the workflows and feedback it provides are useful even if we don't use it as our one enforcement solution for our spec.

Which version is this flag available in? As there doesn't seem to have been a release here since this ticket was opened. Assuming it was released, I think we can close this ticket out for now as it seems to satisfy my initial requirements.

**Comment by LouManglass** [comment]
@solarmosaic-kflorence It's available since at least 9.0.11. It may have sneaked out earlier, but in any case, I'd still recommend getting up to whatever's latest by the time query parameters come in. I understand that's currently a blocker, and doing some of the integration work in the background isn't your highest priority right now. Hopefully we can get you some of that useful feedback as-is at least, and if you have any other CI questions please feel free to ask! We're happy to help with some suggestions and to learn from how y'all work.

I'll close this out per your comment as the flag is released, but please feel free to reopen if you run into any issues or notice something out of line.
