### ISSUE TITLE
title and version

### ISSUE THREAD

**Issue by lvenier** [opticdev/optic#59]
OpenApi format has the 2 following entries :
"title": "Unnamed API",
"version": "1895"

Would be nice to be able to update it from the "api spec" ?
also, why is "share Api" not present in the "api spec" ?

Thanks.

**Comment by matthewhudson** [comment]
Awesome! That sounds good idea, but defaulting to the project's folder name by name.

**Comment by LouManglass** [comment]
@lvenier That's a great catch, thanks for pointing that out! We ask for an API name when running API init, which we store in the optic.yml file. Would this be a sensible title to start with? Once we have a starting title, we can add a way to update it as well on the documentation.

Would you please give me a bit more insight into what "share Api" would do, and how it would help you? I'm not clear on the end goal.

**Comment by ross-nordstrom** [comment]
> We ask for an API name when running API init, **which we store in the optic.yml file**. Would this be a sensible title to start with?

This was my expectation
