### ISSUE TITLE
test optic on Windows 

### ISSUE THREAD

**Issue by c0ncentus** [opticdev/optic#63]
hi,

according to this post i made test optic on windows cause i have another issues on get started on optic, maybe is specificly due to windows env ...  https://github.com/opticdev/optic/issues/61

there is new issue when i success to make 'api init' ...
![oc](https://user-images.githubusercontent.com/25374826/74508615-c1024580-4eff-11ea-9f4a-ff76528ad20c.jpg)

I think something is broken, i make api start, it seem working well.

what you want test on windows ?

**Comment by devdoshi** [comment]
Hi @c0ncentus - glad you were able to get past the initial issues, sorry you've run into some more :/  

Are you saying you are able to use the web interface in Firefox fine if you run `api start` but not if you run `api init`?

Could you send a screenshot of the developer tools console in Firefox when you see the blank page (particularly if you see any errors)? Also, if you navigate to localhost:34444/specs/1 what do you see?

**Comment by c0ncentus** [comment]
url = http://localhost:34444/
![image](https://user-images.githubusercontent.com/25374826/74568039-6c021600-4f77-11ea-86fd-98cbae0e7c20.png)

just i dont see in console 'http://localhost:34444/specs/1/init'
it is possible to open link by default link reactjs devlopment ?

**Comment by c0ncentus** [comment]
<with "api spec">
![image](https://user-images.githubusercontent.com/25374826/74570103-3d3a6e80-4f7c-11ea-9fa6-48c5baf73951.png)
```
app.get('/', (req: any, res: any) => { res.json({ test: 'Api is alive !' }); });
app.get('/Test', (req: any, res: any) => { res.json({ exTest: 'Expected this !' }); });
```
why it don't detect this 2 urls ?  cause it's not api request ?

**Comment by devdoshi** [comment]
Hi @c0ncentus you will need to run `api init` to make sure that Optic can start your node server. Once `api init` is working, then you should run `api start` which will start your node server with Optic watching. Then you need to send actual requests to Optic which should be started at the same address your node server usually starts on. Optic does not try to analyze your code to understand what your API is, it learns by observing actual requests. Does that make sense?

**Comment by c0ncentus** [comment]
ok thanks ! i understand much more thanks ! 

but still something strange ...
I try to change for seing whats happen on update ressource 
```Typescript
import * as express from 'express';
// tslint:disable-next-line: no-duplicate-imports
const app = express();
app.get('/', (req: any, res: any) => { res.json({ test: 'Api is alive !=> Some change' }); });
app.get('/Test', (req: any, res: any) => { res.json({ exTest: 'Expected this !' }); });

app.listen(process.env.OPTIC_API_PORT || 3000, () => { console.log('My API is running...'); });

export default app;
```
first reach ressource on localhost for Optic detect this:
![image](https://user-images.githubusercontent.com/25374826/74958289-009dc580-5409-11ea-9627-2676ccc0cf20.png)

what i get :  

![image](https://user-images.githubusercontent.com/25374826/74958489-4fe3f600-5409-11ea-8a68-954d99584876.png)

I dont get it , can you explain me why Optic detect 304 redirect request please ? : / .

**Comment by devdoshi** [comment]
Express has https://expressjs.com/en/api.html#etag.options.table 

This means, if you use an HTTP client that supports caching by default (like your browser), it will use the  header to detect whether the resource has changed. So the first time you make the request in the browser, it will get a 200 with the body and etag header, second time the browser will send the etag header with the request and the server will respond 304. If you clear the cache in the browser and look at each request you can see this in more detail
