### ISSUE TITLE
Descriptions are not flushed to disk

### ISSUE THREAD

**Issue by javierfvargas** [opticdev/optic#65]
Hi Guys.

Maybe I am doing something wrong, but when I edit the descriptions of my endpoints  the changes are kept in the browser session but never persisted to disk.  So, next time I open the project they are gone.

However, if in the same browser session I edit descriptions of already recorded URLs and then I document a new URL and save it flushes everything. 

I am doing something wrong?

**Comment by acunniffe** [comment]
Hey @javierfvargas I think that’s a small bug for new projects. What’s your current Optic version? We can have a fix out in a day or two

**Comment by devdoshi** [comment]
Hi @javierfvargas sorry for the trouble - can you try @useoptic/cli 7.0.7 and let me know if you still run into the issue?

**Comment by javierfvargas** [comment]
Hi,  It now works.
I was using @useoptic/cli/7.0.5 linux-x64 node-v10.19.0
Then I ran yan upgrade and got to @useoptic/cli/7.0.7 linux-x64 node-v10.19.0.

Thanks guys!

**Comment by acunniffe** [comment]
@javierfvargas great! Happy to help. I also confirmed that those new descriptions from 7.0.7 will write in OpenAPI files if you export with `api generate:oas`
