### ISSUE TITLE
broken "api init" after brew upgrade

### ISSUE THREAD

**Issue by qrkourier** [opticdev/optic#664]
I was running 9.0.15 and upgraded to 9.0.19. Now, I'm trying to do `api init` and getting
> Error: ENOENT: no such file or directory, stat '/home/linuxbrew/.linuxbrew/Cellar/api/9.0.15/libexec/lib/node_modules/@useoptic/cli/node_modules/@useoptic/ui/build/index.html'

Steps to reproduce

```bash
❯ cat /etc/lsb-release                                                    
DISTRIB_ID=Pop
DISTRIB_RELEASE=20.10
DISTRIB_CODENAME=groovy
DISTRIB_DESCRIPTION="Pop!_OS 20.10"

❯ uname -a
Linux kpop4 5.11.0-7612-generic #13~1617215757~20.10~97a8d1a-Ubuntu SMP Thu Apr 1 21:09:17 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

❯ brew uninstall opticdev/optic/api
...

❯ brew install opticdev/optic/api  
...

❯ api version                      
@useoptic/cli/9.0.19 linux-x64 node-v15.14.0

❯ rm -rf .optic/ optic.yml

❯ api init   
/home/kbingham/Sites/netfoundry/github/developer-tools
Is this your API's root directory? (yes/no): yes
What is this API named?: kentest7
[optic] Added Optic configuration to /home/kbingham/Sites/netfoundry/github/developer-tools/optic.yml
Finish setting up your API start task here: http://localhost:34444/apis/1/setup


```

**Comment by qrkourier** [comment]
The web page opens in the browser with the error
>Error: ENOENT: no such file or directory, stat '/home/linuxbrew/.linuxbrew/Cellar/api/9.0.15/libexec/lib/node_modules/@useoptic/cli/node_modules/@useoptic/ui/build/index.html'

Note the 9.0.15 in the non-existent path to the missing file is the version that was installed before the upgrade. I'm guessing there's a problem with `api init` detecting the installed version of `api` or my Homebrew (Linuxbrew port) or both.

**Comment by LouManglass** [comment]
Hi @qrkourier ,

I can't reproduce this generically with Homebrew. A fresh install followed by an `api init` in a new project takes me to the setup page as expected. I wouldn't expect the `api init` command to be searching the Cellars, and I suspect something else is going on here.

I'm pulling a copy of Pop! Linux now to see if there's anything that jumps out at me, and will follow up soon.

**Comment by LouManglass** [comment]
I wasn't able to reproduce this on Pop! Linux 20.10. I was able to install Homebrew on a fresh VM, and `brew install opticdev/optic/api` worked as expected: I ran `api init`, answered the questions, and was taken to a setup page in the browser with no errors.

Since I had to start fresh instead of upgrade, my recommendation would be to try untapping the Optic Homebrew tap and re-tapping. I haven't seen this issue with other upgrades yet, and a fresh tap should mimic a fresh install as closely as possible. Try:

`brew uninstall opticdev/optic/api && brew untap opticdev/optic && brew install opticdev/optic/api`

**Comment by qrkourier** [comment]
Thanks so much for your help. I'm still struggling with the same problem after `brew untap`. In hopes of a workaround, I tried to install the prior version I'd been using 9.0.15 and found it's complicated to do so. I located the Formula in the Optic Keg and the Git revision for 9.0.15. I checked that out as a branch and `brew install api` still installs 9.0.19. I think my next step will be to remove all traces of Homebrew and begin again.

**Comment by LouManglass** [comment]
Oof, I'm sorry to hear that. If it's easier, you may want to use `npm` or `yarn` instead. The Homebrew formula installs the npm package. 

I'm not clear on why you'd see these behaviors on Pop!, and am happy to dive into that with you at some point if you'd like to get to the bottom of it. I also want to respect your time and get you back up as quickly as possible, too, and if there's a quick win like use `npm` I want you to be able to use that.

**Comment by qrkourier** [comment]
Got it working with `npm install --global @useoptic/cli` instead of Homebrew. Incredibly, the problem persisted after running Homebrew's `uninstall.sh && install.sh`! Thank you, again.

**Comment by qrkourier** [comment]
There were a couple of threads I didn't pull that might have led to a root cause here: Pyenv shims or Zsh's executable search $PATH could change the `brew` process environment or mask Homebrew-installed executables with another executable of the same name.

```bash
❯ brew doctor                                  
Please note that these warnings are just used to help the Homebrew maintainers 
with debugging if you file an issue. If everything you use Homebrew for is  
working fine: please don't worry or file an issue; just ignore this. Thanks!
                                                                               
Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if                                                                                         
software packages are installed, and which additional flags to use when        
compiling and linking.                  
                                                                               
Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /home/kbingham/.pyenv/shims/python3-config
  /home/kbingham/.pyenv/shims/python2-config
  /home/kbingham/.pyenv/shims/python3.9-config
  /home/kbingham/.pyenv/shims/python2.7-config
  /home/kbingham/.pyenv/shims/python-config
  /home/kbingham/.pyenv/shims/python3.8-config
  /home/kbingham/.pyenv/shims/ansible-config
                                                                               
Warning: /usr/bin occurs before /home/linuxbrew/.linuxbrew/bin in your PATH.
This means that system-provided programs will be used instead of those
provided by Homebrew. Consider setting your PATH so that
/home/linuxbrew/.linuxbrew/bin occurs before /usr/bin. Here is a one-liner:
  echo 'export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"' >> /home/kbingham/.bash_profile
```

**Comment by LouManglass** [comment]
Oh, interesting...thanks for sharing! I'm glad you were able to get npm working, and sorry for the bother.
