### ISSUE TITLE
[feature] map types

### ISSUE THREAD

**Issue by qrkourier** [opticdev/optic#667]
@LouManglass Please feel free to discard this GitHub issue if not helpful. I hope to capture the feature request we discussed [in Discord](https://discordapp.com/channels/802166068830273536/802167006559862835/832254422737485864).

> Not today, qrk, though it's on our radar. We're finishing up some work "under the hood" to help improve how we process captures, and I know one of the features we want to work on once that's done are map types. I don't have a timeline on that, though we should be able to recognize this as a difference in behavior once the feature is out. That is, there should be a smooth path forward into a better solution.

I am looking for a way to document a nested key name as a variable. Here's an example. In this response the property configIdByConfigTypeId has a value which is a dictionary with variable key names. I'd like to document those variable, nested keys like {{configTypeId}} similarly to the way that URL paths that contain a UUID may be documented as variable. Presently, my spec contains an ever-growing list of presumed predictable keys that are in fact unpredictable.

![2021-04-15_10-04](https://user-images.githubusercontent.com/1434400/114915651-d15acc80-9df1-11eb-8519-4561a58fc874.png)
![2021-04-15_09-57](https://user-images.githubusercontent.com/1434400/114915652-d1f36300-9df1-11eb-92e1-af7e2ccf6612.png)

**Comment by LouManglass** [comment]
Per a user in Discord - 

in their use case, a map key would have an object value containing its own key/value pairs. For them, each map key would have a unique object. That is, each map key would be of type object, but the contents of the object would vary for every unique key. Ideally, we'd support the scenario where map keys could have abstract object values. In this case, the user would expect to add a description to the map key/abstract object value to note that these are all unique objects.
