### ISSUE TITLE
Error: Optic needs more information about your API to continue.

### ISSUE THREAD

**Issue by ArinCantCode** [opticdev/optic#67]
I'm using node - express - typescript

After:
- installing optic
- typing `api init` in powershell in root directory of my API
- setting up all the options available on the page
- typing `api start` in powershell

I'm getting an error: 

```
[optic] Optic needs more information about your API to continue.
This directory already has an optic.yml file.
```

**Comment by devdoshi** [comment]
Hi @ArinCantCode, thanks for the details. What version of the Optic CLI are you using?

When you run `api start`, Optic checks your config, and if it detects an error it puts you into the `api init` flow, but I'm not sure what error it would be hitting.

If you run `DEBUG=optic api start` then you should get additional information about what is failing. Can you reply with that information?

**Comment by ArinCantCode** [comment]
My optic version: @useoptic/cli/7.0.9

I'm sorry but not sure how can i run `DEBUG=optic api start`, could you provide the entire command that i can run in powershell?

**Comment by devdoshi** [comment]
Sorry about that - we want to set the DEBUG environment variable to "optic". According to https://github.com/visionmedia/debug#windows-command-prompt-notes
That means you'd run `set DEBUG=optic & api start` - please let me know if that doesn't work.

**Comment by ArinCantCode** [comment]
My, bad after running in debug mode i got to know that the port was simply blocked and i didn't realize that.

if you mind i would like to ask another question here but it's unrelated to the issue, let me know if questions like should have their own issue or if should head with them somewhere else. 

I saw that importing your own spec was implemented here:  https://github.com/opticdev/optic/issues/21

But can't find how to actually import it. I tried the suggested implementation `api init --import <path>` but that didn't work

**Comment by devdoshi** [comment]
Hey @ArinCantCode glad you got it working. Regarding the functionality in #21 from version 5, we haven't added it into version 7. If you don't mind sending us your spec we can import it and give you further instructions. How does that sound?

**Comment by ArinCantCode** [comment]
That would be awesome! 

How hard is it to import that by myself with provided instructions? We have more than 5 different specs for different API's so importing all of them would be really helpful. 

If providing instructions isn't possible could i provide all my specs? If not that's fine, here is the spec i would like to have imported the most [spec link](https://app.swaggerhub.com/apis/ClashOfStreamers/DubiExAPI/1.0.0)

**Comment by devdoshi** [comment]
Hey @ArinCantCode we have an import endpoint you can post an OpenAPI file to and get back an Optic spec.

Here's an example using httpie that takes a stringified json openapi file located at `openapi.stringified.json` and saves the Optic spec to `specification.json`:

```
http post https://ayiz1s0f8f.execute-api.us-east-2.amazonaws.com/production/oas/coversion/events fileContents:=@openapi.stringified.json -o specification.json
```

Basically it expects to get a JSON object via HTTP POST, with a key called `fileContents` whose value is the escaped contents of your OpenAPI spec.

Once you get it, you can replace your corresponding project's Optic spec file located at `.optic/api/specification.json`

Let me know if you run into any issues, it might be easier to write a nodejs script to send the request if you have to do it a few times. 

Here are the inputs and outputs from my test with your linked spec: https://gist.github.com/devdoshi/15509467c7d0e1a5adbd57346895c1d8

**Comment by ArinCantCode** [comment]
The endpoint works like a charm 👍 

But when trying to see the spec in the browser there seem to be few things not working properly.

After adding the specification You have imported for me and running the command `api start` i end up with this:

![image](https://user-images.githubusercontent.com/38442245/75343833-974f0400-5899-11ea-9f3c-17006a5c7205.png)

The paths seem to not render on the side bar and the response isn't accurate as well.

---

Another part that seems to have strange behavior happens when i make a request to the API. Even if the endpoint seem to be documented after making a request optic shows that there is a new undocumented endpoint with the same path that appears when i hover over one of the requests on sidebar:

![image](https://user-images.githubusercontent.com/38442245/75344192-615e4f80-589a-11ea-9ee5-9d47f7c5939a.png)

**Comment by acunniffe** [comment]
Hey @ArinCantCode are you using some kind of dark mode browser plugin? Your UI looks a little different than mine which might be leading the appearance of things missing. We may have to update the Optic theme. 

Do you want to set up a quick call and debug this with @devdoshi and I? It will probably go faster if we're talking. https://calendly.com/optic-onboarding/chat-with-aidan-clone

**Comment by ArinCantCode** [comment]
Indeed i do use dark mode browser plugin but after disabling it the UI still misses the paths in the sidebar as it did before.

Can't really talk myself in my work space but can listen and respond via chat if that's possible

**Comment by acunniffe** [comment]
@ArinCantCode -- Makes sense. Thanks for toggling that off.  I suspect it has something to do with the OAS import. It's probably getting empty string for those. 

I'll try importing your API later today and see what I can figure out -- I'll circle back later today with my findings and some times.

**Comment by LouManglass** [comment]
@ArinCantCode Hi! I wanted to follow up on this issue. There's been some updates to the Optic tools, and the best thing to do would be to update to the latest version and give `api start` another shot.

If that's not working, is chat/listening still the best method to be in touch? Do you have a different preferred method or time window? I'd be happy to set something up with you.
