### ISSUE TITLE
Crash on accessing full documentation on certain endpoint

### ISSUE THREAD

**Issue by Zomatree** [opticdev/optic#672]
https://gist.github.com/Zomatree/9b1c8be497f3f3b306fcccd74a4fbd4c error logs from `debugOptic()`.

**Comment by LouManglass** [comment]
Thanks for the report! I'll dig into this and let you know what we find.

**Comment by LouManglass** [comment]
Endpoint in question appears to be `GET /api/v7/guilds/{channel_id}/messages/search`, `path_MXOGd1uYwl/methods/GET`. Can reproduce error. Console:

`ln: "did not expect a non-list-item path relative to a list"`

**Comment by LouManglass** [comment]
@Zomatree Thanks for the report, and sorry for the bother. It looks like there's a rendering issue in the current dashboard. I have good news: we're already working on the rendering code, and the latest experimental build appears to render this endpoint correctly. I don't have a timeline for when this will hit a release, though "soon" is accurate.

In the mean time, I created another [specification.json](https://gist.github.com/LouManglass/52a722afce4b6a6e532505a0f53712d9) which doesn't have that endpoint. You can use to replace your `.optic/api/specification.json` for now to remove the endpoint so it's not distracting, and document it again once we release the fix.

Let me know what you think, and if we can do anything else to help.

**Comment by acunniffe** [comment]
To tag along on @LouManglass 's thread -- that endpoint is documented correctly, @Zomatree, there's a bug in optic9 docs viewer which is causing the crash. The new docs viewer in optic10 is much more reliable and shouldn't have issues rending anything you throw at it. 

sneak peek, let us know if you want access to the beta builds in a few days. 

<img width="1718" alt="Screen Shot 2021-03-19 at 9 53 02 AM" src="https://user-images.githubusercontent.com/5900338/115613328-4464b700-a2ba-11eb-89fb-ba2f1c894d17.png">

**Comment by Zomatree** [comment]
Yes please, I would love to check out optic10.

**Comment by LouManglass** [comment]
Hey @Zomatree,

Sorry for the delay, we had a few last issues we wanted to iron out to make sure your whole experience would be smooth. I have good news: Optic 10 is available, and you can upgrade or [install fresh](https://www.useoptic.com/docs/) whenever you get a chance. You should be able to see your documentation working properly by running `api spec` after upgrading, no special steps required.

**Comment by Zomatree** [comment]
Seems to be fixed, Closing.
