### ISSUE TITLE
[Enhancement] Auto .gitignore .optic-daemon.log

### ISSUE THREAD

**Issue by toobulkeh** [opticdev/optic#68]
Upon installation, a log file is created in the local directory but is not automatically gitignored.

`.optic-daemon.log` could be added to .gitignore automatically.

Alternatively, it could be placed in .optic and gitignored there.

**Comment by LouManglass** [comment]
Thanks for the feedback!

Reproduction note: `.optic-daemon.log` is generated by the optic daemon, such as when running `api start`/`api run <task>`.
