### ISSUE TITLE
Contribution guidelines?

### ISSUE THREAD

**Issue by FanaHOVA** [opticdev/optic#69]
Hi, it's a little unclear what the contribution guidelines for the repo are. Are assigned Issues off-limits? Are can they still be worked on? Any commit message convention? Thank you!

**Comment by acunniffe** [comment]
Hey @FanaHOVA we’re working on defining that now. 

Any suggestions?

**Comment by FanaHOVA** [comment]
@acunniffe Few suggestions:

- Add a "Help Needed" label
- Use ["Conventional Commits"](https://www.conventionalcommits.org/en/v1.0.0/) guidelines.
- Are there any tests? Couldn't find any script in the `package.json`.

**Comment by LouManglass** [comment]
@FanaHOVA Hi! Sorry for the delay in response. We've pushed up a start on contributor guidelines and developer setup instructions. Currently, there's some testing around core features though we don't have across the board testing. It's on our radar. I would say assigned issues aren't strictly off-limits, though they're already being investigated and it'd be worth reaching out on the issue first.

Thanks for the references to the "Help Needed" label and the "Conventional Commits" guidelines. We're not standardizing on any of that yet, but it's good food for thought. We appreciate your feedback.
