### ISSUE TITLE
Optic GitBot not working

### ISSUE THREAD

**Issue by karllhughes** [opticdev/optic#763]
I've got Optic running locally and made some changes. My spec file is checked into version control and the GitBot is installed, but when I open up a PR, it is telling me that optic isn't tracking the API spec:

<img width="804" alt="Screen Shot 2021-05-13 at 10 12 22 AM" src="https://user-images.githubusercontent.com/1103622/118145936-bfaa1c00-b3d3-11eb-8b6a-bd534d965826.png">

Here's the PR: https://github.com/karllhughes/sample-node-api/pull/2

As you can see in the specification.json file, I've made changes and recorded them to the spec locally, but Optic doesn't seem to pick them up: https://github.com/karllhughes/sample-node-api/pull/2/files#diff-7802136b9714e36afbf9a1e25be2ac51889bf4a31806f43600ff76c0c73c5f43

Any ideas here?

**Comment by LouManglass** [comment]
Hi @karllhughes 

We're in the process of moving to a new GitHub Action, and you got caught in the middle I'm afraid. I'm sorry about that! I'll get the final documentation polished up and changed over. In the mean time, the GitBot won't work for you as it is. You'll need to use our new Optic Changelog action:

https://github.com/opticdev/optic-changelog

There's two things that are missing from the current Readme as I see it. I have to be away from the desk for a bit, so in case you get there before the instructions are updated:

- In addition to the `GITHUB_TOKEN`, you'll need to add a line for `OPTIC_API_KEY`. While the GitHub token is a built-in secret, that `OPTIC_API_KEY` is what you get from app.useoptic.com. I would suggest storing it in a repository secret so you'll have: `          OPTIC_API_KEY: ${{secrets.OPTIC_API_KEY}}` beneath your GitHub token.
- All actions require versioning. We don't have a version tag right now, so use: `      - uses: opticdev/optic-changelog@c7ab92735c3326b62f6ccf17877e299616de62ac` to fix the SHA hash (which is a good practice anyway).

I'd recommend `on: [pull_request]` as the trigger (and perhaps `workflow_dispatch`) which should get you started with changelogs.

I'm sorry for the confusion, you caught us right in the middle of our move forward, and we were a bit aggressive in stopping the old service. We wanted to make sure new users got on board the best version, we just didn't quite get is in front of everyone first :)

**Comment by karllhughes** [comment]
@LouManglass thanks for the quick response, and that all makes sense.

Will the GitBot eventually be updated? Or what's the plan there?

I'm asking because I'm working with @acunniffe to write a blog post on how to use the Optic GitBot, so I want it to be updated with the most recent correct information. If the GH Action is a replacement for the GitBot, I'll specify that.

Thanks!

**Comment by LouManglass** [comment]
@karllhughes Ah, thanks for the context! The Action is a full replacement in favor of the GitBot. Definitely specify the GitHub Action. 

Since we're still cutting over to the GitHub Action, I'd be happy to jump on a quick chat to discuss this in further detail feel free to [grab some time](https://calendly.com/d/m86c-wjb9/30-minute-meeting) or follow up to organize a higher-bandwidth discussion. If there's anything we can do to help make that smooth, I'm available.

**Comment by karllhughes** [comment]
Perfect, got it working. A couple notes on the GH action in your readme:

- `opticdev/optic-changelog` needs to have a `ref`. I used `opticdev/optic-changelog@main`
- Users don't need to enter a `GITHUB_TOKEN`, that's automatically supplied by GitHub. Probably obvious to frequent GH Action users, but I'm new to them, so just a minor note.

Here's the entire action I used in case it's helpful: 

```
name: optic-changelog
on: [pull_request]
jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: opticdev/optic-changelog@main
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          OPTIC_API_KEY: ${{secrets.OPTIC_API_KEY}}
```

Thanks for the help, I'll close this!
