### ISSUE TITLE
Asterisk in the path of an endpoint

### ISSUE THREAD

**Issue by nikita2206** [opticdev/optic#849]
An asterisk in the path of an endpoint currently breaks Optic's UI when, after it's seen me navigating to that endpoint I try to add it in the diff tool. 
The full path in my case looks like `/v1/foo/**`.

**Comment by LouManglass** [comment]
Oof! I'll give that a closer look and have an update for you in a day. If you have any other details to add, please let me know and I'll be sure to include them in my testing.

**Comment by niclim** [comment]
Thanks for raising this @nikita2206 - I've got a fix up here https://github.com/opticdev/optic/pull/850 where I also identified a couple of other issues that should also be fixed with that PR! We'll follow up with you when there's a new version that has this problem fixed!

**Comment by nikita2206** [comment]
Thanks for such a quick response!

**Comment by LouManglass** [comment]
Thanks for checking in on the PR as well, and the added notes. We'll keep you posted as we work through a proper fix and get a new version tested and released.

**Comment by niclim** [comment]
Hi @nikita2206 - we've just released optic version `10.0.5` which should fix this problem (you should be able to have `*` in endpoints without crashing)

I did want to follow up on this comment you left here https://github.com/opticdev/optic/pull/850#issuecomment-853993249
> I wonder if this also tackles the issue with having complex regexps in the ignore rules? For example I was trying to use a negative lookahead pattern which is something like (?!do not match) and I was getting an error saying that my pattern is invalid.

Can you give some examples or use-cases where you'd want to have negative lookups (or other regexp patterns that the ignore rules currently don't support)? This would be helpful to understand where there's gaps and how we could address them. Thanks!

**Comment by nikita2206** [comment]
Hey @niclim thanks! We have a haproxy in front of all web services, so that they all are accessible by the same domain but with different path prefixes. I just wanted to exclude one of the services by doing a negative match on its path prefix. I must say the use case is weird and I'm absolutely fine without being able to do that (I simply deploy Optic for the specific service only, not for everything that's behind haproxy). On the other hand it does look like the library that Optic uses for matching paths support using arbitrary regexps so maybe Optic could relatively easily add that support.

**Comment by niclim** [comment]
Thanks for elaborating. The reason this is slightly more tricky is that the user input for ignore patterns are strings (i.e. in the `.ignore` file or in the UI ignore flow), and strings and regexp are handled differently for both cases (for escaped characters, and things like `/api/:apiId/todos` would need to be specified by a group) - meaning that if we want to have a single interface, and support negative lookaheads - the ignore rules parsing would change.

Path-to-regexp supports regexp, but it doesn't have the same interface - it still effectively treats regex as a passthrough to the javascript constructor
Example:
```javascript
> pathToRegexp('/api/:apiId') // string
/^\/api(?:\/([^\/#\?]+?))[\/#\?]?$/i

> pathToRegexp(/\/api\/:apiId/) // regexp - with escaped slashes
/\/api\/:apiId/
```

It's probably much more common to want to match a specific route (using `:pathParameter`) than a negative look up (or more complex regex patterns). That being said, we could potentially look at adding in escape hatches somehow to allow for more specialized cases. (We would also want to balance this such that it isn't too complex to work with custom ignore rules, etc).

**Comment by niclim** [comment]
I'm going to close this out - but feel free to reopen this if there's any other issues you find.
