### ISSUE TITLE
Unexpected behavior when learning new endpoint underneath existing endpoint

### ISSUE THREAD

**Issue by jshearer** [opticdev/optic#907]
I'm having an issue learning the following endpoint: `POST /api/person/public-specs/v2`. I already have an endpoint at `POST /api/person/public-specs`. The issue is that the new path seems to erroneously learned as `POST /api/person/public-specs/{specId}`.

### Existing endpoints:
<img width="946" alt="Screen Shot 2021-06-21 at 1 25 03 PM" src="https://user-images.githubusercontent.com/4368270/122802999-17ba2500-d294-11eb-8f1d-3b70a18f98da.png">

### Network request made:
<img width="653" alt="Screen Shot 2021-06-21 at 1 17 38 PM" src="https://user-images.githubusercontent.com/4368270/122803033-21dc2380-d294-11eb-8823-8df796aa19a4.png">

### Optic Diff UI:
<img width="634" alt="Screen Shot 2021-06-21 at 1 25 39 PM" src="https://user-images.githubusercontent.com/4368270/122803106-328c9980-d294-11eb-97f0-474dc0745c78.png">
<img width="1261" alt="Screen Shot 2021-06-21 at 1 25 44 PM" src="https://user-images.githubusercontent.com/4368270/122803109-33253000-d294-11eb-9c79-4c415b2d7beb.png">

Now I suppose looking at this again, given that I _do_ have a `GET /api/person/public-specs/{specId}` endpoint, the assumption that the same format would hold is reasonable, and I should probably change my endpoint to something like `/api/person/public-specs-v2` or something like that. Nevertheless, this feels like an unexpected assumption, especially given that I have no way to override it. Thoughts?

**Comment by LouManglass** [comment]
I'm of the opinion that this is performing as expected, but that our expectations may need to be adjusted. That is, given what you showed me, I would absolutely expect `POST /api/person/public-specs/v2` to be eaten by`POST /api/person/public-specs/{specId}`. That being said, I could definitely see this happening in the wild - trying to learn a discrete endpoint that matches a pattern after documenting the pattern, and yeah, we don't have a way to break those out after the fact.

Stepping through this, I think if I "lost" traffic I'd expect to have a way to see what traffic was hidden from me in the UI. Optic has surfaced what it thinks is important to me on the happy path (diffs/unmatched URLs). My expectations aren't met, so let me opt to dig in. Show me everything Optic saw (request foo) and if hidden, show me why (matched to endpoint bar by pattern matching) so I can then take some action (foo doesn't match bar, let me break out this endpoint/match it to baz?)

There may be a simpler first cut at this that doesn't involve a lot of work.

This is one of those things that feels like it shouldn't happen, but probably does pretty often, and should have some way of digging under the surface to resolve it without greatly changing the "happy path".
