### ISSUE TITLE
Null content type crashes the review diff flow

### ISSUE THREAD

**Issue by jshearer** [opticdev/optic#929]
I'm getting a crash in [new-regions-interpreter.ts](https://github.com/opticdev/optic/blob/develop/workspaces/ui-v2/src/lib/new-regions-interpreter.ts#L68) when I try to learn a new shape for an existing endpoint. It looks like `location.inRequest.contentType` is undefined.

<img width="1036" alt="Screen Shot 2021-06-24 at 4 02 53 PM" src="https://user-images.githubusercontent.com/4368270/123325128-a681a880-d505-11eb-986b-77996d03858f.png">

Here's the debug file with the interaction in question:

[debug-optic-1624564000735-tame-wolverine-62.json.zip](https://github.com/opticdev/optic/files/6711805/debug-optic-1624564000735-tame-wolverine-62.json.zip)

**Comment by niclim** [comment]
A fix for the diff page crashing is in this PR https://github.com/opticdev/optic/pull/940 - however there's more work to do to handle the diff found in this capture - i.e.
- A GET request was made with a request body {} + learnt
- A subsequent GET request with no request body was sent (with null) - learning this causes two endpoints to show up (with the same id, i.e. same pathId and method

**Comment by LouManglass** [comment]
The fix for the crash has shipped, minimum version 10.1.1. We'll let this sit open to resolve the rest of the issue.

**Comment by niclim** [comment]
This is now fixed with the latest version of optic - `10.2.0`
